- packages/indexer-agent/src/agent.ts
In accordance with the arbitration charter (in progress) the POIs will now be for the first block of the epoch that the allocation is being closed in.  
In practice: The first block of the epoch is fetched by calling the EpochManager contract and then converted to a block hash using the Ethereum provider. This value is then used to fetch POIs to be submitted with allocation close.
> indexer-agent: Submit POI for first block of last epoch

- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/network.ts
- packages/indexer-common/src/errors.ts
- yarn.lock
This PR adds gas management tools to the indexer agent to allow better control of gas prices and a more robust transaction management process.
Several gas management startup arguments are introduced to define the transaction resubmission behavior.  
- **gas-increase-timeout (seconds)**: The time limit after which to resubmit the transaction with more gas.
- **gas-increase-factor**: Percent to bump the gas when resubmitting.
- **gas-price-max (gwei)**: The maximum gas price for a resubmitted transaction.
- **transaction-attempts**: The maximum number of transaction retries to attempt.
Transactions are now retried upon failure; depending on the failure mode the transaction configuration will be adjusted before resubmitting.  For example, if a transaction exceeds the `gas-increase-timeout` …
> Indexer agent: Managing failed or stuck transactions

- docs/networks.md
> Update graph-node version to 0.23.1

- packages/indexer-common/src/network-subgraph.ts
- packages/indexer-service/src/server/index.ts
When profiling the indexer service performance and memory usage just processing `/network` requests, I noticed that most time and memory is spent and allocated in urql (and wonka).
Since all the `/network` endpoint does is forward to another endpoint (local or elsewhere), we don't really need to have a GraphQL-aware client into the mix. This commit switches network subgraph execution from urql to plain HTTP / axios.
> indexer-common, indexer-service: Optimize /network execution

- packages/indexer-cli/src/commands/indexer/status.ts
- packages/indexer-common/src/indexer-management/client.ts
- packages/indexer-common/src/indexer-management/resolvers/indexer-status.ts
Remove failing check for the removed /channel-messages-inbox endpoint.
Closes #224
> indexer-cli: Remove check for channel-messages-inbox endpoint

- packages/indexer-common/src/network-subgraph.ts
Some subgraph queries successfully respond with error codes. However,
the return type of the subgraph query was inconsistent with the
structure of the data being returned in the error case. This would
result in error logs that omit the error message because the parsed
response body would result in a type error instead. This change prevents
the type error from occurring such that the log shows the expected error
message.
> indexer-agent: Catch subgraph query errors

- packages/indexer-agent/src/network.ts
The query for subgraph deployments used to determine which are worth
indexing was subject to timing out due to its complexity. This change
paginates the query rather than taking the first 1000. This has the
added benefit of reducing the possibility of missing deployments.
> indexer-agent: Paginate query for subgraph deployments

- docs/networks.md
Update README for the latest version 0.17.0
> Update for the latest version 0.17.0

- .github/workflows/indexer-cli-image.yml
- Dockerfile.indexer-cli
Should be run with tty mode so we can enter into the container later
> Dockerfile for indexer-cli

- packages/indexer-common/package.json
- yarn.lock
This should fix CI in this PR and on `main` as well.
> indexer-common: Update cost-model dependency to fix the build

- packages/indexer-common/package.json
- yarn.lock
Bump @graphprotocol/cost-model from 0.1.11 to 0.1.14
> Upgrade cost-model lib

- docs/networks.md
Update the suggested versions of the indexer components:
- Mainnet: v0.19.3
- Testnet: v0.20.0
> docs/network: Update recommended indexer component versions

- docs/networks.md
0.28.1's fix did not work as intended, updating to 0.28.2
> Update to use 0.28.2

- packages/indexer-agent/src/agent.ts
- packages/indexer-common/src/indexer-management/monitor.ts
- remove extra periodic check on latest network epoch
- fix typing for latest epoch
> indexer-agent,-common: fix resolve latest epoch

- docs/errors.md
- docs/networks.md
Update 
- testnet's network parameter and indexer component recommended versions
- Env var for `--epoch-subgraph-endpoint` set for subgraph `graphprotocol/goerli-epoch-block-oracle`
- error.md for IE070
> docs: update network.md and errors.md

- .github/workflows/indexer-agent-image.yml
- .github/workflows/indexer-cli-image.yml
- .github/workflows/indexer-service-image.yml
- docs/action-queue.md
Quick update to add references to the recently added `actions update` support.
> docs: Update action queue docs, include recent `actions update` support

- README.md
- packages/indexer-agent/README.md
- packages/indexer-agent/src/__tests__/indexer.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/indexer.ts
- packages/indexer-cli/src/__tests__/util.ts
- packages/indexer-cli/src/allocations.ts
- packages/indexer-cli/src/commands/indexer/allocations/create.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/cost-models.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/indexing-rules.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/poi-disputes.ts
- packages/indexer-common/src/indexer-management/allocations.ts
- packages/indexer-common/src/indexer-management/client.ts
- packages/indexer-common/src/indexer-management/resolvers/allocations.ts
- packages/indexer-common/src/indexer-management/subgraphs.ts
- packages/indexer-service/src/commands/start.ts
- packages/indexer-service/src/server/__tests__/server.test.ts
This reverts commit 94b54274ef4801899a8f644dd4a716d71689fc43.
From PR #512
> Revert "indexer-agent,-service: remove index-node configs"

- packages/indexer-cli/src/actions.ts
- packages/indexer-cli/src/command-helpers.ts
- packages/indexer-common/src/indexer-management/resolvers/actions.ts
- Improve error message for action update input parsing
- Accept '0' POI value
> indexer-cli: Improve action update input parsing

- packages/indexer-common/src/indexer-management/types.ts
Add avalanche, polygon, celo, & optimism to chain alias and ID lookups.
> indexer-common: Add avalanche, polygon, celo, & optimism to chain alias lookups

- packages/indexer-common/src/network.ts
Code suggestion for [this comment](https://github.com/graphprotocol/indexer/pull/472#discussion_r961883141) on #472
> Proposal to flatten nested try/catch block

- docs/feature-support-matrix.md
- docs/networks/mainnet.md
> Release `graph-node` v0.30.0 on `mainnet.md`

- packages/indexer-agent/src/agent.ts
> agent: Re-fetch allocations for accurate reconciliation

- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.ts
- packages/indexer-common/src/indexer-management/allocations.ts
> common: account rewards when resolving unallocate action delta

- packages/indexer-common/src/allocations/query-fees.test.ts
- packages/indexer-common/src/allocations/query-fees.ts
- Update partial-vouchers data structure
- Encode partial-vouchers using JSON
- Improve logging around redeeming receipts for vouchers or partial-vouchers
- Update partial voucher encoding tests
> indexer-common: Update partial-vouchers encoding

- packages/indexer-agent/src/agent.ts
This PR makes the reconciliation loop aware of the Exponential Rebates transition period by gracefully handling failed calls to `channelDisputeEpochs`.
Once Exponential Rebates have been deployed to all networks, this special handling can be removed from the code, alongside with all calls to deprecated contract functions.
> Gracefully handle Exponential Rebates transition

- docs/networks/arbitrum-goerli.md
- docs/networks/ethereum-goerli.md
Updates subgraph deployment values to the latest version (exponential rebates).
> docs: update network subgraph deployment values

- .github/workflows/publish-native-binaries.yml
- update ci workflow to have manual trigger
> update ci workflow for publish binaries

- .github/workflows/ci.yml
- .github/workflows/publish-native-binaries.yml
Thie PR attempts to update the OS packages on ubuntu OS for dependencies used by builds such as glibc and fix nodejs/rust bindings.
> Fix ci pipeline and update OS dependencies on Ubuntu

- packages/indexer-common/src/indexer-management/actions.ts
- Improve graph-node connection testing at startup: use exponential retry and exit process if connection fails. 
- Relax strictness of local deployment and validation of network subgraph (the local deployment may not be needed)
- Improve failure mode if network registration fails or ensuring global index rule fails: log critical message and exit instead of entering unhandled promise rejection.
- Add `protocolNetwork` to action update constraint.
- Fix "try...catch" block setup around staking.channelDisputeEpochs().
> indexer-agent: Various bug fixes and improvements to error handling

- packages/indexer-agent/package.json
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-cli/package.json
- packages/indexer-common/package.json
- packages/indexer-common/src/utils.ts
- packages/indexer-native/package.json
- packages/indexer-service/package.json
- yarn.lock
Note to reviewers: 
Merge only after https://github.com/graphprotocol/common-ts/pull/106 is merged and published to NPM.
> Upgrade common-ts to v2.0.3

- packages/indexer-agent/README.md
- packages/indexer-cli/README.md
- packages/indexer-service/README.md
Fixes #743 
**Problem**: Most README.md files are outdated and no longer match the available command line options and arguments.
**Solution** : 
- Updated graph-indexer README.md
- Updated indexer-service README.md
- Updated indexer-agent README.md
> Update readme files

- packages/indexer-agent/package.json
- packages/indexer-cli/package.json
- packages/indexer-common/package.json
- packages/indexer-common/src/indexer-management/__tests__/helpers.test.ts
- packages/indexer-common/src/network.ts
- packages/indexer-native/package.json
- packages/indexer-service/package.json
- packages/indexer-service/src/commands/start.ts
- packages/indexer-service/src/server/__tests__/server.test.ts
- yarn.lock
- Upgrade dependency tag in package.json files for all packages
- Update usage of `connectContracts` function
> Upgrade common-ts dependency

- docs/feature-support-matrix.md
Recreating Pedro's fork PR. Updated commit messages
> Add Optimism to support matrix

- .gitignore
- packages/indexer-integration-tests/.eslintignore
- packages/indexer-integration-tests/.eslintrc.js
- packages/indexer-integration-tests/.prettierrc.json
- packages/indexer-integration-tests/LICENSE
- packages/indexer-integration-tests/README.md
- packages/indexer-integration-tests/jest.config.js
- packages/indexer-integration-tests/package-lock.json
- packages/indexer-integration-tests/package.json
- packages/indexer-integration-tests/src/global-setup.ts
- packages/indexer-integration-tests/src/global-teardown.ts
- packages/indexer-integration-tests/tests/bootstrap.spec.ts
- packages/indexer-integration-tests/tsconfig.json
- yarn.lock
Small PR to add the integration test package to the lerna workspace.
> indexer-integration-tests: start integration test package

- packages/indexer-common/src/allocations/__tests__/tap.test.ts
Added more unit tests as per #888
> Add more tests into tap.tests

- packages/indexer-common/src/indexer-management/types.ts
- Add `bsc`, `linea`, `scroll`, and `base` to chain id lookups.
> common: Add support for BSC, Base, Linea, Scroll

- docs/networks/arbitrum-one.md
- docs/networks/arbitrum-sepolia.md
- docs/networks/ethereum-sepolia.md
Updates https://github.com/graphprotocol/indexer/pull/918 with cleaner commit messages (I ran into catastrophic git failure on trying to interactive rebase the other PR 😆 )
> Add missing addresses and resolve table formatting issues in network docs

- lerna.json
- packages/indexer-agent/package.json
- packages/indexer-cli/package.json
- packages/indexer-common/package.json
- packages/indexer-service/package.json
Version bump for changed packages.
> agent,common,cli,service: bump versions

- docs/networks/arbitrum-one.md
- docs/networks/arbitrum-sepolia.md
- docs/networks/ethereum-mainnet.md
- docs/networks/ethereum-sepolia.md
For both all testnet/mainnet, recommend v0.21.3
> Docs: recommend v0.21.3

- packages/indexer-common/src/indexer-management/monitor.ts
- packages/indexer-common/src/indexer-management/resolvers/allocations.ts
Resolves #894
Just don't try to generate a POI when we are working with an unsupported network.
Also removes duplicate resolvePOI function.
> common: allow closing of allocations on unsupported networks

- lerna.json
- packages/indexer-agent/package.json
- packages/indexer-cli/package.json
- packages/indexer-common/package.json
- packages/indexer-service/package.json
> release-0.21.4 - version bump

- packages/indexer-common/src/graph-node.ts
Fix the indexerStatus query workaround.
> common: fix indexerStatus (paused) query

- packages/indexer-agent/src/db/migrations/12-add-scalar-tap-table.ts
- packages/indexer-common/src/query-fees/models.ts
Reverts graphprotocol/indexer#974
> Revert "feat: add error_log into scalar_tap_receipts_invalid"

- packages/indexer-common/src/allocations/tap-collector.ts
> fix: check ravs every 15 minutes

- docs/feature-support-matrix.md
- packages/indexer-common/src/indexer-management/types.ts
docs & common: add support for zora, mode, moonbeam
Updated feature support matrix and types.ts files.
> docs & common: add support for zora, mode, moonbeam

- docs/feature-support-matrix.md
Updated feature support matrix to include rootstock and removed cosmos
> docs & common: add support for rootstock, remove cosmos

- docs/networks/arbitrum-one.md
- docs/networks/arbitrum-sepolia.md
Use new IPFS URL, https://ipfs.thegraph.com
> Update IPFS URL in docs
