- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/network.ts
This PR introduces a minimum query fees collected threshold for claimable allocations. The configurable threshold, defaulting to 0, will serve to avoid sending unnecessary claim transactions for allocations that haven't collected any query fees.
> indexer-agent: Allocation only claimed if it has collected query fees

- packages/indexer-agent/package.json
- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/network.ts
- packages/indexer-cli/package.json
- packages/indexer-common/package.json
- packages/indexer-service/package.json
- yarn.lock
Before, we'd only reconcile if any of the inputs changed, but sometimes the agent finishes reconciling but should do another pass sooner than e.g. the next epoch.
This is the case, for instance, if allocations needed to be closed to free up stake for new allocations; in this case the agent will currently reconcile allocations per deployment but if allocations of a later deployment free up stake that could've been used for an earlier deployment, then we need to reconcile again asap.
On the "asap": It should be possible to flag when there is more reconciliation work to do, but identifying whether that is even possible is hard. Simply reconciling again every 2 minutes, without necessarily resyncing all input data is a decently simple workaround.
This commit therefore polls the different …
> Sync agent inputs independently and reconcile reliably every 2 minutes

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/indexer.ts
This adds passing the epoch start block number to the `proofOfIndexing` query, which is being added to graph-node in https://github.com/graphprotocol/graph-node/pull/2100.
This change is necessary so that we can reliably obtain a POI even if the graph-node block store doesn't have the Ethereum block in question. This fixes the main problem in #186. For another improvement (allowing indexers to deal with legitimate 0x0 POIs by closing allocations with manual intervention), we'll create a separate issue.
> indexer-agent: Update to new `proofOfIndexing` API (#186)

- packages/indexer-agent/src/network.ts
Because we currently pass the `BigNumber` object to the query for claimable allocations directly, it's serialized as an object and results in a GraphQL query error:
```bash
[2021-01-11 15:38:51.061 +0000] ERROR (IndexerAgent/1 on indexer-agent-56fd576fc6-zqtdq): Failed to query claimable indexer allocations
component: "Network"
indexer: "0xd3a3Fa4B73e5007a8adEf6CCdFC8D05C06A76035"
operator: "0xd159dbA0d6909778C821B81eCF83B6790743A953"
err: {
"type": "IndexerError",
"message": "Failed to query claimable indexer allocations",
"stack":
IndexerError: Failed to query claimable indexer allocations
at Object.indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:97:12)
at Network.<anonymous> (/opt/indexer/packages/indexer-agent/dist/network.js:336:46)
at Generator.next (<anonymous>) …
```
> indexer-agent: Fix how query fee threshold is passed to claimable allocations

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/indexer.ts
This properly fixes #186. We'll still want to capture these cases and allow indexers to retry them later through `graph indexer` or resolve them manually.
> indexer-agent: Never close allocations on zero POI, retry 10 times (#186)

- packages/indexer-agent/package.json
- packages/indexer-cli/package.json
- packages/indexer-common/package.json
- packages/indexer-service/package.json
- yarn.lock
ethers 5.0.26 includes a fix for https://github.com/ethers-io/ethers.js/issues/1208, which should remove the unresolved promise rejections we've seen in #183.
Before we merge this, we should also bump common-ts to a new release that includes https://github.com/graphprotocol/common-ts/pull/60.
> *: Update ethers to 5.0.26 (#183)

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/types.ts
This feature allows indexers to index e.g. their own subgraphs or other subgraphs they deem interesting that are not published on chain (yet). They won't be able to claim rewards (neither indexing nor querying) for these but indexing and querying on its own may be worth it in some cases.
Usage:
```sh
graph-indexer-agent ... --offchain-subgraphs QmA...,QmB...,QmC...
```
> indexer-agent: Allow to index subgraphs that are not on chain

- packages/indexer-agent/src/__tests__/indexer.ts
- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/indexer.ts
- packages/indexer-agent/src/types.ts
- packages/indexer-cli/src/commands/indexer/disputes/get.ts
- packages/indexer-cli/src/disputes.ts
- packages/indexer-common/src/indexer-management/__tests__/poi-disputes.ts
- packages/indexer-common/src/indexer-management/client.ts
- packages/indexer-common/src/indexer-management/resolvers/poi-disputes.ts
This PR updates the allocation POI monitoring algorithm to avoid checking allocation POIs that have already been identified as potential disputes and stored in the indexer db (`POIDisputes` table).  In addition the indexer-cli has been updated, so disputes can be filtered when fetching them, new structure `indexer disputes get <status> <minimumAllocationClosedEpoch>`.
> Indexer-agent, indexer-cli: Improve allocation POI monitoring efficiency, allow filtering of disputes from cli

- packages/indexer-agent/package.json
- packages/indexer-cli/package.json
- packages/indexer-common/package.json
- packages/indexer-service/package.json
- packages/indexer-service/src/commands/start.ts
- yarn.lock
There's two parts to this:
1. Reduce the allocation syncing interval (and make it configurable), from 10s to 120s.
2. Update common-ts to the latest version that includes a fix for `reduce` eventuals suddenly stopping to work.
> indexer-service: Improve allocation syncing

- .github/workflows/indexer-agent-image.yml
- .github/workflows/indexer-service-image.yml
- lerna.json
- packages/indexer-agent/package.json
- packages/indexer-agent/src/query-fees/allocations.ts
- packages/indexer-cli/package.json
- packages/indexer-common/package.json
- packages/indexer-common/src/query-fees/allocation-utils.ts
- packages/indexer-common/src/query-fees/index.ts
- packages/indexer-service/package.json
- packages/indexer-service/src/query-fees/allocations.ts
To track allocations and associated receipts, the agent creates allocation summaries in the db for every allocation it opens. It then links incoming receipts to these based on the allocation ID. The problem is, these allocation summaries are only created when allocations are created. Most, if not all indexers, however, already have allocations from before 0.15.0 and there's no summaries for these.
This commit ensures allocation summaries are created when flushing receipts, to make sure receipts that were created before 0.15.0 (or manually without the agent running) can be flushed to the database.
> *: Ensure allocation summaries for pre-existing allocations

- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/query-fees/allocations.ts
Prior to this change, the claim threshold would only apply to calling `claim`, but it makes sense to also apply it to `redeem` so that only amounts that are worth collecting are collected.
> indexer-agent: Apply allocation claim threshold to redeeming vouchers

- packages/indexer-service/src/commands/start.ts
- packages/indexer-service/src/server/index.ts
This only enables the `/network` endpoint when the service is started with `--serve-network-subgraph`. It also adds a dedicated auth token for `/network` requests that is optional.
> indexer-service: Make /network optional, use dedicated auth token

- packages/indexer-agent/src/commands/start.ts
this fixes the agent from crashing when the --offchain-subgraphs command line parameter contains the empty string.
> offchain subgraphs parameter fix

- packages/indexer-agent/src/commands/start.ts
Error introduced in 5febd002ec4668d9f1679f6d116f53fa836188a0
> indexer-agent: Fix syntax error in offchain-subgraphs option

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/network.ts
This implements three changes:
- Adds a `closeAndAllocate` function to `network.ts`, wrapping the contract interactions and performing the relevant safety checks
- Adds a `reallocate` function to `agent.ts`, which gets the POI, calls `network.closeAndAllocate` and claims receipts for the closed allocation
- Modifies `reconcileDeploymentAllocations` in `agent.ts` to a) use `agent.reallocate` in place of an `agent.closeAllocation` and then `network.allocateMultiple` and b) remove the logic that does a staggered closure of parallel allocations (no longer relevant)
This results in `indexer-agent` using the `closeAndAllocate` function on the Staking contract to renew an expired but still desirable allocation rather than first `closeAllocation` and then `allocateFrom` in two separate …
> indexer-agent: implement closeAndAllocate within allocation reconciliation logic

- packages/indexer-cli/src/commands/indexer/status.ts
The `indexer status` output would include styling characters in the yaml
and json output formats. This would result in fields such as
`"status": "\u001b[32mup\u001b[39m",` instead of `"status": "up",`. This
PR only applies the styling characters when the table output format is
selected.
> indexer-cli: Remove styling characters from non-table output

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/network.ts
This is just a result of running yarn and committing the results so that they aren't included in unrelated PRs. There should probably be a CI check for this.
> indexer-agent: Fixup formatting

- k8s/base/indexer-agent/service.yaml
- k8s/base/indexer-service/service.yaml
This is to avoid exposing both services to the internet directly. We've also made the experience that `LoadBalancer` services add extra latency.
> k8s: Use ClusterIP instead of LoadBalancer for internal services

- packages/indexer-agent/src/agent.ts
@fordN reported the agent throwing the following error when reallocating (`closeAndAllocate`) on testnet:
```Failed to reconcile indexer and network
component: "Agent"
err: {
"type": "IndexerError",
"message": "Failed to reconcile indexer and network",
"stack":
IndexerError: Failed to reconcile indexer and network
at Object.indexerError (/Users/ford/thegraph/workspaces/temp/indexer/packages/indexer-common/src/errors.ts:156:10)
at Agent.<anonymous> (/Users/ford/thegraph/workspaces/temp/indexer/packages/indexer-agent/src/agent.ts:296:18)
at Generator.throw (<anonymous>)
at rejected (/Users/ford/thegraph/workspaces/temp/indexer/packages/indexer-agent/src/agent.ts:6:65)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
"code": "IE005", …
```
> indexer-agent: fix out of bounds lookup in for loop

- packages/indexer-agent/src/network.ts
When reallocating (`closeAndAllocate`), the GRT that we free up when closing the existing allocation becomes immediately available for the new allocation within the batched call.
This PR updates the agent to add the GRT amount of the existing allocation to the check against the Indexer's available tokens.
Without this fix, an indexer would need to have a buffer of free tokens equal to or in excess of the existing allocation or else the agent won't submit the reallocation transaction.
> indexer-agent: add existing allocation GRT to freeStake check when reallocating

- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/query-fees/allocations.ts
Add --voucher-expiration to configure the time (in seconds) after which a voucher with too few query fees is permanently deleted. Until then, keep retrying to redeem it to give the indexer a chance to adjust their `--allocation-claim-threshold`.
As requested by Jim on Discord.
> indexer-agent: Retry low fee query fee vouchers later

- packages/indexer-agent/src/commands/start.ts
URL parse function provide empty username and password fields if auth data wasn't supplied in auth URL.
But ether.js considers empty username and password as a valid auth data and forms basic auth header with that.
I have faced that some ethereum node operators (without auth) fails to handle such requests.
ether.js maintainers reported that it's not a bug and they are not going to fix this in their lib. So fix for this case should be implemented on graphprotocol/indexer side - https://github.com/ethers-io/ethers.js/pull/1697#issuecomment-869036939
This PR adds checking if username and password fields both empty, then `undefined` would be supplied to ether.js which would disable adding empty auth header to requests.
/fix https://github.com/graphprotocol/indexer/issues/256
> Pass undefined as auth data if there's empty user and password

- packages/indexer-agent/src/commands/start.ts
This formatting error was introduced prior to the formatting Ci check.
This change fixes the formatting so that future PRs will not have CI
failures for unrelated formatting issues.
> indexer-agent: Format start.ts

- docs/networks.md
A few users have tried specifying the network ID instead of the network name, and reported the following error from `indexer-service`/`indexer-agent`:
```
Error: invalid network (argument="network", value="4", code=INVALID_ARGUMENT, version=providers/5.1.0)
```
> docs: use ethereum network name instead of id

- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/indexer.ts
- packages/indexer-cli/src/commands/indexer/status.ts
- packages/indexer-common/src/indexer-management/client.ts
- packages/indexer-common/src/indexer-management/resolvers/indexer-status.ts
- packages/indexer-common/src/indexing-status.ts
- packages/indexer-common/src/network-subgraph.ts
- packages/indexer-common/src/types.ts
- packages/indexer-service/src/commands/start.ts
This change adds an Indexer Deployments section to the `indexer status` command. Example output:
```
Indexer Deployments
┌────────────────────────────────────────────────┬────────┬─────────┬────────────┬─────────┬─────────┬───────────────────┬──────────────────────┬─────────────────────┐
│ deployment                                     │ synced │ health  │ fatalError │ node    │ network │ latestBlockNumber │ chainHeadBlockNumber │ earliestBlockNumber │
├────────────────────────────────────────────────┼────────┼─────────┼────────────┼─────────┼─────────┼───────────────────┼──────────────────────┼─────────────────────┤
│ QmVqMeQUwvQ3XjzCYiMhRvQjRiQLGpVt8C3oHgvDi3agJ2 │ false  │ healthy │ -          │ default │ mainnet │ 12421076          │ 12864751             │ 11101016            │ …
```
> indexer-cli: Show indexer deployment status

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/indexer.ts
I've updated this PR to no longer make assumptions about whether to index and allocate towards failed subgraphs. This has significantly reduced the scope of the changes to just one small commit.
Changes: 
- Continue to sync any deployments that are allocated to on the network. Prior to this change subgraph deployments would be removed from the infra immediately upon a rule change leading to a desired deployment removal even though continued syncing may be needed in order to close the allocation. 
----
For posterity: the old notes from the PR that included assumptions around not wanting to allocate to failing subgraphs. Currently only case 1 is handled. 
The agent eagerly deploys subgraphs and creates allocations based on its indexing rules; however, there are some cases where the agent …
> Indexer-agent: Don't remove subgraph deployments with active allocations

- docs/networks.md
Reverts graphprotocol/indexer#307
Blocked by bug in receipt fetching
> Revert "graph-node 0.24.0 version bump"

- .github/workflows/indexer-agent-image.yml
- .github/workflows/indexer-cli-image.yml
- .github/workflows/indexer-service-image.yml
- docs/errors.md
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/indexer.ts
- packages/indexer-agent/src/network.ts
- packages/indexer-cli/src/commands/indexer/rules/set.ts
- packages/indexer-common/src/indexer-management/models/indexing-rule.ts
- packages/indexer-common/src/indexer-management/resolvers/indexer-status.ts
- Remove "jannis/*" branches from github workflow triggers. 
- Default to unlimited max transaction attempts in the indexer agent to avoid orphaned transactions. 
- Only allow setting parallel allocations to 1 for indexing rules to prepare for full deprecation of the parallel allocations feature. 
- Treat deployments assigned to node = `null` or `undefined` as `removed`, so they are filtered out of the `actDeployments` array.
> Various smaller updates

- package.json
- packages/indexer-agent/CHANGELOG.md
- packages/indexer-agent/package.json
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/network.ts
- packages/indexer-cli/CHANGELOG.md
- packages/indexer-cli/package.json
- packages/indexer-common/CHANGELOG.md
- packages/indexer-common/package.json
- packages/indexer-native/CHANGELOG.md
- packages/indexer-native/package.json
- packages/indexer-service/CHANGELOG.md
- packages/indexer-service/package.json
- yarn.lock
This PR adds support for type 0x2 transactions (specified in EIP-1559). In order to include this support all Ethers dependencies have been updated to 5.4.*.  Legacy transaction types are still supported 
Type 0x2 transactions were introduced with the recent London fork and have the potential to facilitate a more robust and predictable transaction gas pricing model. For information about how type 0x2 transactions work and their implementation rollout across the ecosystem see this great [cheatsheet](https://hackmd.io/@q8X_WM2nTfu6nuvAzqXiTQ/1559-wallets).
> Indexer agent: Support type 0x2 transactions (EIP-1559)

- packages/indexer-agent/src/__tests__/indexer.ts
- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/indexer.ts
- packages/indexer-agent/src/migrations/03-poi-disputes-add-subgraph-deployment-id.ts
- packages/indexer-agent/src/network.ts
- packages/indexer-common/src/indexer-management/__tests__/cost-models.ts
- packages/indexer-common/src/indexer-management/__tests__/indexing-rules.ts
- packages/indexer-common/src/indexer-management/__tests__/poi-disputes.ts
- packages/indexer-common/src/indexer-management/models/poi-dispute.ts
- packages/indexer-common/src/indexer-management/resolvers/poi-disputes.ts
- Relax the non-null restrictions on reference PoIs in the PotentialDisputes model.
- Use references_unavailable state to describe the case where at least one reference poi is unavailable and the allocation PoI has not been validated.
> indexer-agent: Add references_unavailable state to potential disputes

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/network.ts
- packages/indexer-cli/src/commands/indexer/status.ts
Part of the epic to deprecate parallel allocations this PR adds logic to reconcileDeploymentAllocations() to close any parallel allocations as they become old enough.
> indexer-agent: Close parallel allocations (instead of renewing)

- packages/indexer-cli/src/allocations.ts
- packages/indexer-cli/src/commands/indexer/status.ts
- packages/indexer-cli/src/rules.ts
- packages/indexer-common/src/indexer-management/resolvers/indexer-status.ts
- Create formatting and display functions for indexer allocations. 
- Commify status output numbers.
> Indexer-cli: Formatting improvements to status output

- packages/indexer-agent/src/network.ts
- Get events emitted in tx for varification from either receipt.events or receipt.logs.
- Use correct transaction type number for legacy transactions.
> indexer-agent: Various minor cleanup changes in network module

- packages/indexer-service/src/queries.ts
- packages/indexer-service/src/server/index.ts
- packages/indexer-service/src/types.ts
This change sets the Graph-Attestable header on query results based on
that of the graph-node response. By default this header will be set to
false and no attestation will be provided. See [GIP 20](https://hackmd.io/@CGmldHLrTRaYRnAva-HoPQ/S1W2vMjEt)
> Add support for unattestable query responses

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/network.ts
This implements these changes:
- Adds a `claimMany` function to `network.ts`, wrapping the contract interactions and performing the relevant safety checks
- Instead of iterating through claims and calling each one, call `claimMany` and pass in a batch
- Adds `--rebate-claim-threshold` and `--rebate-claim-batch-threshold` as options
Thanks @fordN!
> indexer-agent: implement batch rebate claiming using claimMany

- .gitignore
- package.json
- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/indexer.ts
- packages/indexer-agent/src/network.ts
- packages/indexer-agent/src/query-fees/allocations.ts
- packages/indexer-agent/src/query-fees/transfers.ts
- packages/indexer-cli/src/client.ts
- packages/indexer-common/package.json
- packages/indexer-common/src/errors.ts
- packages/indexer-common/src/indexer-management/__tests__/cost-models.ts
- packages/indexer-common/src/indexer-management/models/cost-model.ts
- packages/indexer-common/src/indexer-management/models/indexing-rule.ts
- packages/indexer-common/src/indexer-management/models/poi-dispute.ts
- packages/indexer-common/src/query-fees/models.ts
- packages/indexer-service/package.json
- packages/indexer-service/src/query-fees/allocations.ts
- packages/indexer-service/src/query-fees/transfers.ts
- packages/indexer-service/src/server/index.ts
- yarn.lock
- Include buffer period for deployments; deployments will now continue to be synced for 1 day after allocation close in case the indexer wants to keep that deployment fresh or the gateway needs to query it. 
- Fix gas price bumping on transaction retry.
- Remove vestiges related to parallel allocations. 
- Wrap register in a retry function.
- Update .gitignore. 
- Apply formatting suggestions.
> indexer-agent: Introduce deployment syncing buffer and fix transaction retry gas price bumping

- Dockerfile.indexer-service
Like indexer-agent's Dockerfile, we should specify an `ENTRYPOINT` in indexer-service's Dockerfile instead of a `CMD`. This is because the `CMD` is overwritten when you specify command line arguments in the `docker run indexer-service ...` form. Currently the image falls back to the ENTRYPOINT defined in the base image, which is `node`, which means that arguments get passed to node instead of the `indexer-service` process.
This PR fixes that, making the default `docker run` behaviour intuitive/run as expected.
> indexer-service: docker entrypoint instead of cmd

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/indexer.ts
- packages/indexer-agent/src/network.ts
- packages/indexer-agent/src/query-fees/allocations.ts
- Updates defaults for batch rebate claiming to set the individual rebate threshold to `200` GRT, and the batch claim threshold to `2000` GRT. This should prevent claiming unprofitable rebates, and also increases claim efficiency by leveraging batching.
- This sets a maximum batch size of 100 claims, preventing constructing transactions that are larger than the block gas limit
Should fix #330
> indexer-agent: add max batch size, tweak claim defaults

- packages/indexer-agent/src/indexer.ts
- packages/indexer-agent/src/network.ts
Improved logging around fetching indexing rules from the Indexer Management endpoint and matching them with subgraph deployments fetched from the subgraph. 
Added to help debug when there are issues with fetching subgraphDeployments published to the network, fetching indexer rules, or matching the deployments to their corresponding rules.
> indexer-agent: Add logging for indexing rule fetching and matching

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/indexer.ts
- packages/indexer-agent/src/network.ts
Important updates to `network.subgraphDeploymentsWorthIndexing()`:
- Fix bug that led to false empty result returned from `subgraphsWorthIndexing()`.
- If subgraph deployments query returns empty array throw error instead of gracefully returning an empty array.
- Pass error message to IndexerError.cause.
Small improvements to `reconcileDeploymentAllocations()`:
- Update naming  to be more clear: `worthIndexing` --> `worthAllocating`.
> indexer-agent:  Fix subgraph deployments batch query processing

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/network.ts
- packages/indexer-agent/src/query-fees/allocations.ts
- packages/indexer-common/src/allocations/types.ts
Adding extra info to the logs
- IPFS hash to `Reconcile deployment allocations`
- Rebate claim amount to `Claim tokens from the rebate pool for allocation`
- Latest block or fatal errors to `Received a null or zero POI for deployment`
- Added attempts to `redeem query fee voucher`
Reduce logs 
- lowered levels for `Allocation rebate rewards`
- added conditions for other logs such as `Reconcile`
Plan for next steps
- more logger stuff
-- ask indexers how they'd change the logs
-- quantify and analyze log messages
- Investigate IE055 in `redeem query fee voucher`
> Indexer agent logger improvement 

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/types.ts
Adds an override to allow allocations to the network subgraph. This is useful for the local testing environment.
> Add option to allocate on network subgraph

- Dockerfile.indexer-agent
- Dockerfile.indexer-cli
- Dockerfile.indexer-service
- package.json
- Update runtime image versions since `graphql@16.2.0` requires node >= 12.22.0 (recommend ^v16.0.0). 
- Specify engine in package.json to improve handling of node runtime version too low.
> Upgrade node runtime image versions

- packages/indexer-service/src/server/deployment-health.ts
- packages/indexer-service/src/server/index.ts
This route handles only GET requests. It returns an HTTP 200 response if the deployment in question has not failed and is caught up to the chain head. Otherwise, a 500 is returned with different error messages depending on what is wrong.
This can be used to check the health of specific subgraph deployments in environments where the indexing status API is too complicated and simple, URL-based health checks are the only option (e.g. Cloudflare load balancers, k8s readiness probes, status pages).
> indexer-service: Add /subgraphs/health/:deployment route

- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/network.ts
- packages/indexer-agent/src/utils/balance-monitor.ts
- packages/indexer-agent/src/utils/index.ts
- packages/indexer-common/src/errors.ts
This is refreshed every 2 minutes and can be used by indexers to set up alerting for when their operator is running out of ETH to make transactions.
> indexer-agent, indexer-common: Add live metric for operator ETH balance

- .github/workflows/ci.yml
- .github/workflows/indexer-agent-image.yml
- .github/workflows/indexer-cli-image.yml
- .github/workflows/indexer-service-image.yml
- packages/indexer-service/src/server/deployment-health.ts
There was an extraneous `{` in the query that caused graph-node to trip over.
> Fix indexing status query used for health endpoint

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/network.ts
Previously, indexers find agents needing a few minutes before picking up rules, so a common practice was to restart indexer-agent after setting the rules. 
This PR speeds up the frequency of checking indexing rules, and triggers `Reconcile Deployments` within 20 seconds of changing the rules. -> indexers would not need to restart the agent as often. 
Rebased to `ford/local-rule-by-gns`
> Indexer-agent, indexer-cli: indexing rules applied instantly

- Dockerfile.indexer-agent
- packages/indexer-agent/CHANGELOG.md
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/network.ts
- packages/indexer-agent/src/query-fees/allocation-exchange.ts
- packages/indexer-agent/src/query-fees/allocations.ts
- packages/indexer-common/src/allocations/types.ts
- Added automatic batching of query voucher redemptions
- Added `--voucher-redemption-threshold`, `--voucher-redemption-batch-threshold` and `--voucher-redemption-max-batch-size` for controlling voucher batching behaviour
- Sets `NODE_OPTIONS="--max-old-space-size=1536"` by default for the `indexer-agent` Docker container. This is appropriate for an environment with 2GB of RAM.
- Added `--rebate-claim-max-batch-size` to make max rebate claim batch size configurable.
- Move `parseGRT` for GRT-value flags into yargs coersion to standardise the location of flag transforms
- Improved validation of rebate batch claim parameters
> indexer-agent: Batched voucher redemptions

- packages/indexer-agent/src/network.ts
- packages/indexer-cli/src/allocations.ts
- packages/indexer-cli/src/commands/indexer/status.ts
- packages/indexer-common/src/allocations/types.ts
- packages/indexer-common/src/indexer-management/client.ts
- packages/indexer-common/src/indexer-management/resolvers/indexer-status.ts
- packages/indexer-service/src/allocations.ts
The `signalledTokens` field describes the amount of GRT signalled on a subgraph or subgraph deployment. `signalAmount` describes the amount of signal shares on a subgraph, which is based on the bonding curve and hence don't correspond 1:1 to the amount of GRT signalled.
It is therefore much more intuitive to use `signalledTokens` for the `minSignal` threshold in indexing rules.
> Use signalledTokens instead of signalAmount for minSignal threshold

- packages/indexer-agent/src/db/migrations/05-indexing-rules-add-subgraph-id.ts
Update migration `05` to properly handle existing rules subgraphIdentifierType values.
> indexer-agent: Fix subgraph identifier migration

- docs/networks.md
- packages/indexer-cli/src/__tests__/references/help.stdout
Update doc to recommend indexers use the latest tag on Testnet.  Once multiple indexers have successfully tested on Testnet (or wherever they are comfortable) I'll update the recommended Mainnet setup as well.
> docs: Update recommended indexer software component versions for testnet

- packages/indexer-common/src/indexer-management/client.ts
- packages/indexer-common/src/indexer-management/models/poi-dispute.ts
Observing logs related to errors from null values for POIs returned from the graph-node.
```
"type": "IndexerError",
"message": "Failed to store potential POI disputes"
"stack":
IndexerError: Failed to store potential POI disputes
at Object.indexerError (/Users/hopeyen/projects/indexer/packages/indexer-common/src/errors.ts:160:10)
at Indexer.<anonymous> (/Users/hopeyen/projects/indexer/packages/indexer-agent/src/indexer.ts:375:19)
at Generator.next (<anonymous>)
at fulfilled (/Users/hopeyen/projects/indexer/packages/indexer-agent/src/indexer.ts:5:58)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
"code": "IE039",
"explanation": "https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie039",
"cause": {
"type": …
```
> indexer-common: allow reference proof null in schema

- packages/indexer-cli/src/commands/indexer/status.ts
- packages/indexer-common/src/indexer-management/client.ts
Currently if there is a deployment in postgres db with no start block, indexers cannot query `status`
```
Error fetching status information: [GraphQL] Cannot return null for non-nullable field ChainIndexingStatus.earliestBlock.
```
It makes sense to allow null for earliestBlock so that indexers can still query `status` with these deployments.
> indexer-cli, indexer-common: earliestblock allow null

- .github/workflows/ci.yml
- packages/indexer-agent/.eslintrc.js
- packages/indexer-agent/package.json
- packages/indexer-cli/.eslintrc.js
- packages/indexer-cli/package.json
- packages/indexer-cli/src/commands/indexer/cost/get.ts
- packages/indexer-cli/src/commands/indexer/cost/set/model.ts
- packages/indexer-cli/src/commands/indexer/cost/set/variables.ts
- packages/indexer-cli/src/commands/indexer/rules/delete.ts
- packages/indexer-cli/src/commands/indexer/rules/get.ts
- packages/indexer-cli/src/commands/indexer/rules/set.ts
- packages/indexer-cli/src/rules.ts
- packages/indexer-common/.eslintrc.js
- packages/indexer-common/package.json
- packages/indexer-common/src/indexer-management/__tests__/indexing-rules.ts
- packages/indexer-common/src/indexer-management/resolvers/indexing-rules.ts
- packages/indexer-common/src/subgraphs.ts
- packages/indexer-native/package.json
- packages/indexer-service/.eslintrc.js
- packages/indexer-service/package.json
- yarn.lock
- Update resolvers to convert subgraph deployment ids to base58 format before saving into the DB. 
- Update eslint and add semi-colon rules.
> Indexer-common: Always use base58 format for deployment ids 

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/indexer.ts
- packages/indexer-common/src/indexing-status.ts
- packages/indexer-common/src/types.ts
With more checks to the indexing status, we discovered a missing type conversion that leads to the following error. With a more explicit conversion the issue should be resolved.
```
[2022-03-14 17:53:09.657 +0000] WARN (IndexerAgent/1 on c0a257d65da3): Proof of indexing could not be queried
attempt: 8
retriesLeft: 3
err: "[GraphQL] Invalid value provided for argument `blockNumber`: String(\"4663370\")"
```
> bug-fix: parse graphQL of indexing status

- packages/indexer-agent/src/indexer.ts
Currently, when there's a new deployment, indexer assign it to a node randomly.
To improve index-node usage, assign new deployments to index-nodes with the least amount of deployments assigned. 
- if there are nodes unused, assign to them randomly as before
- If all nodes have been used, assign to the node with the lowest usage
Future ideas to implement: affinity (config file with rules), network-specific nodes, energy, features, ...
> indexer-agent: assign deployment to nodes based on usage

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/network.ts
Adding a safety check before opening an allocation: if the subgraph deployment wasn't last closed with a zero POI, the agent will skip allocating it, otherwise just proceed as normal.
> Agent check previous allocation POI and does not open if zero

- docs/networks.md
This release has more than a month, this should be merged asap.
> docs: Update graph-node to 0.25.2

- packages/indexer-agent/package.json
- packages/indexer-service/package.json
- packages/indexer-service/src/commands/start.ts
- yarn.lock
The latest versions of `ReadPkg` and `@thi.ng/cache` are ECMAScript modules which are tricky to maintain compatibility with while we are still using commonjs imports. We'll continue to stick to these versions until we can upgrade the entire project to ESM (ongoing work).
> Revert ESM packages for compatibility with Commonjs

- package.json
- packages/indexer-agent/package.json
- packages/indexer-cli/package.json
- packages/indexer-common/package.json
- packages/indexer-native/.eslintignore
- packages/indexer-native/.eslintrc.js
- packages/indexer-native/jest.config.js
- packages/indexer-native/package.json
- packages/indexer-service/package.json
- yarn.lock
I've included several improvements to the build process here, but the main change was to significantly reduce the size of our npm packages by specifying which files are included.
- Specify files to include in published packages using the `files` array in each package.json.
- Use consistent formatting of `main` and `types` values. 
- Use lint and prettier in the `indexer-native` package to ensure consistent formatting.
> *: Reduce build size, include formatting where missing

- packages/indexer-agent/package.json
- packages/indexer-cli/package.json
- packages/indexer-cli/src/__tests__/references/help.stdout
- packages/indexer-native/native/Cargo.toml
- packages/indexer-native/package.json
- packages/indexer-service/package.json
- Upgrade `neon` cargo dependency in `indexer-native`
- Include `/bin` in published package files for CLI packages
- Fix `indexer-cli` executable name
- Fix `indexer-cli` --help test
> Upgrade @graphprotocol/cost-model, improve publish setup

- .github/workflows/publish-native-binaries.yml
- packages/indexer-agent/package.json
- packages/indexer-cli/package.json
- packages/indexer-cli/src/__tests__/references/help.stdout
- packages/indexer-common/package.json
- packages/indexer-common/src/indexing-status.ts
- packages/indexer-native/lib/index.js
- packages/indexer-native/native/Cargo.toml
- packages/indexer-native/package.json
- packages/indexer-service/package.json
- yarn.lock
We use [neon](https://github.com/neon-bindings/neon) to package rust binaries with node-bindings (as Node add-on modules), so they can be called by our indexer component packages. The system works well, but has a few shortcomings the most commonly reported point of friction has been in compiling the binaries on our users machines (see **Related Issues** below). In order to compile there are a few requirements to be installed on the machine: Rust, python, node-gyp, and in some cases nan.  This PR aims to avoid these requirements/issues by precompiling the binaries on various machines and for various versions of the Node ABI and publishing these binaries to the GitHub releases page and making the defaulting the install process download the relevant precompiled binary instead of compiling it …
> indexer-native: Install uses precompiled binaries hosted on GitHub releases

- packages/indexer-native/package.json
- ARM machines can build the module from source
- Pre-compiling to ARM targets is still not operational so `npm i -g @graphprotcol/indexer-native`, for instance,  will not work on ARM machines
> indexer-native: Declare support for ARM in package.json

- packages/indexer-common/src/indexing-status.ts
small catch for the potential BlockPointers being returned as string that isn't being parsed to types properly using https://github.com/graphprotocol/indexer/blob/06f0c4465aa4ead000a6ec3db94b44ff551a0a94/packages/indexer-common/src/indexing-status.ts#L35-L38
> indexer-common: start block query - ensure numeric type

- Dockerfile.indexer-agent
- Dockerfile.indexer-cli
- Dockerfile.indexer-service
- packages/indexer-common/package.json
`node:16.13.1-slim` images use an older version of GLIBC not compatible with the
precompiled native binaries. 
This fixes docker image builds, but we'll need to find a solution so that users can build the packages on older versions of linux with older GLIBC versions.
> Dockerfiles: Update base images to node:16.15-bullseye-slim

- .github/workflows/publish-native-binaries.yml
Improve compatibility with linux distros.
> CI: Use older version of Ubuntu to precompile native binaries

- packages/indexer-agent/config.yaml
- packages/indexer-agent/package.json
- packages/indexer-agent/src/commands/start.ts
- yarn.lock
** RECREATING THIS PR** from PR #395 as the CI pipeline didn't like building off of a fork.
This pull requests implements file-based configuration for the indexer agent such that the configuration file supplements base defaults for a cluster. The idea here is that default values for mainnet, rinkeby, etc can be supplied as code in the repository, with more important parameters being injected via environment variables and CLI flags.
The order of precedence is as follows:
CLI flags
Environment variables
Configuration file parameters
F.eks. running indexer-agent with a configuration file containing ethereum: https://ethereum-node-0:8545 and setting INDEXER_AGENT_ETHEREUM to https://ethereum.hosted.service/accountid/, the effective setting would be https://ethereum.hosted.service/accountid/.
> Indexer Agent Configuration by File

- packages/indexer-common/src/network.ts
```
action: "ClaimMany"
err: {
"type": "IndexerError",
"message": "Failed to claim allocation",
"stack":
IndexerError: Failed to claim allocation
at indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:143:12)
at Network.<anonymous> (/opt/indexer/packages/indexer-common/dist/network.js:993:60)
at Generator.next (<anonymous>)
at fulfilled (/opt/indexer/packages/indexer-common/dist/network.js:5:58)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
"code": "IE016",
"explanation": "https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie016",
"cause": {
"type": "TypeError",
"message": "_a.gt is not a function",
"stack":
TypeError: _a.gt is not a function
at …
```
> indexer-common: query fee explicitly check for numeric type

- packages/indexer-service/src/commands/start.ts
- packages/indexer-service/src/queries.ts
- packages/indexer-service/src/query-fees/allocations.ts
- packages/indexer-service/src/query-fees/index.ts
The goal is to enable monitoring of the fees paid for queries.
The change adds detailed query logs for paid queries w/:
Deployment (base58 IPFS hash)
Query execution time
GQL query / variables
GRT fees
Note that to add the GQL query response time measurement to Axios as recommended in the documentation, I had to do some non-TSisms. Hopefully there is a better way to do that.
> indexer-service detailed query logs

- packages/indexer-cli/src/rules.ts
For offchain subgraphs, indexing rules fields like `allocationAmount` doesn't really matter, so the table view is more than enough. For a clearer output, we simply print out offchain subgraphs' list of identifiers.
> Indexer-cli: only print identifier for offchain subgraphs

- packages/indexer-cli/src/__tests__/indexer/rules.test.ts
- packages/indexer-cli/src/__tests__/references/indexer-cost-set-invalid-arg.stdout
- packages/indexer-cli/src/allocations.ts
- packages/indexer-cli/src/command-helpers.ts
- packages/indexer-cli/src/commands/indexer/connect.ts
- packages/indexer-cli/src/commands/indexer/rules/delete.ts
- packages/indexer-cli/src/commands/indexer/status.ts
- packages/indexer-cli/src/cost.ts
- packages/indexer-cli/src/disputes.ts
- packages/indexer-cli/src/rules.ts
To keep consistent between writing in the terminal and file, we remove all the colors codes when someone is outputting JSON or YAML
> indexer-cli: remove colors from yaml and json ouputs

- README.md
- packages/indexer-agent/README.md
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-common/src/indexer-management/actions.ts
- packages/indexer-common/src/indexer-management/client.ts
- packages/indexer-common/src/indexer-management/monitor.ts
When an indexer uses AUTO management mode, the agent automatically approve actions for the worker to execute. 
To avoid worker executing those transactions right away, we provide `indexer-agent` optional start up parameters:
- `--auto-min-batch-size`: require a minimum batch size 
- `--auto-max-wait-time`: wait for certain minutes after the first approved actions' update time
These 2 parameters are useful when an indexer let the agent perform automatic batched transactions, allow time for indexers to modify actions, and in particular save gas costs on allocations. 
Another condition we added is that actions will still execute right away when an on-chain transactions is expiring - the agent automatically produce and approve reallocation actions and it seems sensible to allow worker to …
> Actions Queue: add auto batch options and conditions

- packages/indexer-agent/package.json
- packages/indexer-agent/src/__tests__/indexer.ts
- packages/indexer-cli/package.json
- packages/indexer-cli/src/__tests__/util.ts
- packages/indexer-common/package.json
- packages/indexer-common/src/indexer-management/__tests__/actions.ts
- packages/indexer-common/src/indexer-management/__tests__/cost-models.ts
- packages/indexer-common/src/indexer-management/__tests__/indexing-rules.ts
- packages/indexer-common/src/indexer-management/__tests__/poi-disputes.ts
- packages/indexer-native/package.json
- packages/indexer-service/package.json
- packages/indexer-service/src/server/__tests__/server.test.ts
- yarn.lock
The latest address book is required to run an indexer on Goerli, so the contracts dependency was updated to the version which includes it, v1.13.0.  Common-ts also depends on @graphprotocol/contracts, so it was upgraded as well.
> Upgrade @graphprotocol/contracts dependency

- packages/indexer-agent/src/db/migrations/09-actions-expand-failure-reason-varchar.ts
Alter 'Actions' table to expand the size of the `failureReason` column, so error strings will fit. 
STRING(1000) --> STRING(5000)
> indexer-agent: Create DB migration to expand failureReason column

- packages/indexer-cli/src/__tests__/indexer/rules.test.ts
- packages/indexer-cli/src/__tests__/references/indexer-rules-invalid-set-arg.stdout
- packages/indexer-cli/src/command-helpers.ts
- packages/indexer-cli/src/commands/indexer/rules/set.ts
- packages/indexer-cli/src/rules.ts
When using wrong arguments for `indexer rules set`, the error message 
`TypeError: INDEXING_RULE_PARSERS[key] is not a function` 
is not very clear. 
Improve the error message to specify the invalid key: when provided a non-existing attribute, return messages like
`Indexing rule attribute 'allocatoinAmount' doesn't exist, please check spelling`
for next step: can make suggestions using modules like `spellchecker-cli`
> indexer-cli: indexing rule parser error catch

- docs/networks.md
https://github.com/graphprotocol/graph-node/releases/tag/v0.27.0
> docs/network: Update recommended graph-node version

- docs/networks.md
Include instructions for how to use the graph explorer gui to stake in the protocol and add an operator wallet.
> README: Add graph explorer instructions to 'Approving and Staking' section

- docs/errors.md
- packages/indexer-common/src/errors.ts
- packages/indexer-common/src/indexer-management/allocations.ts
- packages/indexer-common/src/indexer-management/monitor.ts
- packages/indexer-common/src/indexer-management/resolvers/allocations.ts
Resolves #444 
Currently the failure reason column gets populated by the error log message if a transaction fails. These log messages were designed to be logged to stdout not to be stored in a DB column. Occasionally the messages seem to hit the limit `SequelizeDatabaseError: value too long for type character varying(1000)`.  
We update the failure reasons to be shorter strings. For the actions that failed due to an existing `IndexerError`, we simply store the error code as `IE0XX` so people can look up the reasons and solutions if provided. We also added more variations of IndexerError to cover the failure cases here with the action manager.
> Shorten failure reason stored

- packages/indexer-agent/src/__tests__/indexer.ts
- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/indexer.ts
- packages/indexer-agent/src/types.ts
- packages/indexer-common/src/actions.ts
- packages/indexer-common/src/indexer-management/allocations.ts
- packages/indexer-common/src/indexer-management/monitor.ts
- packages/indexer-common/src/indexer-management/resolvers/actions.ts
- packages/indexer-common/src/network.ts
- packages/indexer-common/src/subgraphs.ts
- packages/indexer-service/src/server/__tests__/server.test.ts
With the ultimate goal of including meaningful reason strings for each action added to the actions queue a number of changes have been made in this PR. 
The process of resolving which deployments are worth allocating towards has been updated to now result in an array of allocation decisions with length equal to the number of subgraph deployments on the network, including both toAllocate and not toAllocate decisions (rather than an array of only subgraph ids to allocate to).  
```typescript
AllocationDecision {
declare deployment: SubgraphDeploymentID
declare toAllocate: boolean
declare ruleMatch: RuleMatch
}
```
In addition, the process of resolving allocation actions has been updated. `reconcileAllocations`  and `reconcileDeploymentAllocations` have been replaced with …
> indexer-common,indexer-agent: Include reason for actions being added to queue

- packages/indexer-cli/src/actions.ts
- packages/indexer-cli/src/commands/indexer/actions/get.ts
- packages/indexer-common/src/actions.ts
- packages/indexer-common/src/indexer-management/__tests__/actions.ts
- packages/indexer-common/src/indexer-management/actions.ts
- packages/indexer-common/src/indexer-management/client.ts
- packages/indexer-common/src/indexer-management/resolvers/actions.ts
- packages/indexer-common/src/types.ts
Use `orderBy` and `orderDirection` inputs for user provided ordering of actions queries.  This API is meant to be similar to other GraphQL APIs, specifically the [subgraph query API](https://thegraph.com/docs/en/querying/graphql-api/#sorting).
> indexer-common: Update actions query ordering inputs

- packages/indexer-cli/src/commands/indexer/actions/approve.ts
- packages/indexer-common/src/actions.ts
- packages/indexer-common/src/indexer-management/client.ts
Resolves #449 
If there's more than one actions with queued status, indexers can use `indexer-cli` as such to approve all the queued actions
```
./bin/graph-indexer indexer actions approve queued
```
If there's no queued actions, expect error `Failed to process action ids, check queue for available actions`.
Alternatively we can add a new query type for `approveActions` to include parameter for `ActionStatus`?
> indexer-cli: command to batch approve queued

- docs/errors.md
- packages/indexer-common/src/indexer-management/allocations.ts
- packages/indexer-common/src/indexer-management/resolvers/allocations.ts
- packages/indexer-common/src/subgraphs.ts
Updating logic check in the indexer agent per [GIP0027](https://forum.thegraph.com/t/gip-0027-create-altruistic-allocations-and-close-stale-allocations/3217/6) by simply removing the constraint on 0.
> indexer-common: allow 0 staked allocations

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/indexer.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/cost-models.ts
- packages/indexer-common/src/indexer-management/models/cost-model.ts
- packages/indexer-common/src/indexer-management/resolvers/cost-models.ts
- packages/indexer-service/src/server/cost.ts
Received report on query to cost model still returns null when global cost model has been set. 
- Update indexer-serivce `costModels` queries to return global cost models for the deployments without cost model defined.
- Add basic tests in `indexer-common` as we debug the potential issue
> Set default for cost models plurals, add tests

- packages/indexer-agent/src/commands/start.ts
- packages/indexer-common/src/errors.ts
- packages/indexer-common/src/subgraphs.ts
The bug affected indexing-rules using `minSignal` thresholds without a 'maxSignal' threshold set.  In this scenario the indexer-agent would find all rules above the `minSignal` threshold not worthy of allocating to because they didn't also have a `maxSignal` threshold set. This check has now been fixed to only use the `maxSignal` threshold if one is set. 
I also took the opportunity to make some minor updates to: 
- update error reference page url: use `main` branch 
- use consistent subgraph naming convention: `indexer-agent/${networkSubgraphDeployment.ipfsHash.slice(-10)}`.
> indexer-common: Fix bug in isDeploymentWorthAllocatingTowards()

- packages/indexer-common/src/subgraphs.ts
The max signal conditional is an unused feature adding unnecessary complexity to the allocation decision logic . This PR removes the usage of it from isDeploymentWorthAllocatingTowards() ahead of deprecating it in the APIs.
> indexer-common: Remove max signal check, towards deprecating max signal

- packages/indexer-service/src/query-fees/allocations.ts
Currently, the `indexer-service` do not persist receipts with zero fees.
They skip the processing queue as the `AllocationReceiptManager.add` method early exists if they have no fees.
https://github.com/graphprotocol/indexer/blob/dde26d93b88f38c62b0d216a79f5225b1619d709/packages/indexer-service/src/query-fees/allocations.ts#L98-L110
There might be use cases for keeping those receipts around, such as testing and development environments.
This PR removes the early return condition so that every receipt enters the processing queue.
Future improvements may address the auto-removal of such receipts after a given time.
> indexer-service: Persist receipts with zero fees

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/indexer.ts
- packages/indexer-cli/README.md
- packages/indexer-cli/src/commands/indexer/cost/set/model.ts
Remove `ensureGlobalCostModel` and `reconcileCostModel` from indexer agent as they clutter the agent without any real changes towards the cost models. 
Now indexers should simply set global default cost model through indexer-CLI such as
```
graph indexer cost set model global [path]/basic.agora
```
> Indexer-agent: remove fallback to hardcode default file

- packages/indexer-common/src/indexer-management/allocations.ts
- packages/indexer-common/src/indexer-management/resolvers/allocations.ts
Always create subgraphs with the following naming scheme: `indexer-agent/${deployment.ipfsHash.slice(-10)}`.
> indexer-common: Use consistent deployment names

- packages/indexer-service/src/query-fees/allocations.ts
I'm not sure what else got deleted from [https://github.com/graphprotocol/indexer/commit/f7fa658b6903a1320ac9006912fbb80af61fca7d](https://github.com/graphprotocol/indexer/commit/f7fa658b6903a1320ac9006912fbb80af61fca7d) that might have been important, I'll go over the rest later.
> security: resurrect comment deleted in f7fa658b

- packages/indexer-cli/src/__tests__/references/indexer-help.stdout
- packages/indexer-cli/src/actions.ts
- packages/indexer-cli/src/commands/indexer/actions/delete.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.ts
- packages/indexer-common/src/indexer-management/client.ts
- packages/indexer-common/src/indexer-management/resolvers/actions.ts
- Add `indexer actions delete` command to delete actions by IDs in indexer-cli
example
```
$HELP - graph indexer actions delete [options] [<actionID1> ...]
./bin/graph-indexer indexer actions delete 13 16 37
✔ Processed input parameters
✔ 3 actions deleted
./bin/graph-indexer indexer actions delete 8 9 10                            
✔ Processed input parameters
✖ [GraphQL] Delete action failed: No action items found with id in [8,9,10]
```
If useful, we can delete all actions by a certain status, but I'm worried if it is too easy? Indexers could also `get` with filters and then feed in action ids as an array
> AQI: actions delete command

- docs/networks.md
There was a regression in 0.28.0 for Graph Nodes run with the example `docker-compose.yaml`. This new version has a fix.
> Update to 0.28.1

- packages/indexer-common/src/subgraphs.ts
It's currently a bit tricky to debug allocation decisions. To improve debug process this PR adds an additional trace log at the beginning of `isDeploymentWorthAllocatingTowards()` which includes the deployment's data and the matching rule it is being evaluated against.
> indexer-common: Trace log data used to evaluate each deployment

- docs/errors.md
- packages/indexer-common/src/allocations/types.ts
- packages/indexer-common/src/errors.ts
- packages/indexer-common/src/indexer-management/monitor.ts
- packages/indexer-common/src/indexer-management/resolvers/allocations.ts
- packages/indexer-common/src/indexing-status.ts
- Add more explicit error logs
- Avoid querying block information when action (`unallocate` or `reallocate`) is forced and poi is provided.
> indexer-common: re-organize error logging

- packages/indexer-common/src/actions.ts
- packages/indexer-common/src/indexer-management/resolvers/actions.ts
Adds a new validation step to `executeQueueOperation`, which prevents the current action from entering the queue if it is found to be a retry from a previously failed attempt.
To do so, we query the database for actions with a `failed` status from the past 24h and check if it contains the current action.
> indexer-common: Avoid recreating recently failed actions

- docs/networks.md
Updating network parameters to reflect current values on Goerli testnet:
- Epoch length is 554 blocks which is ~1h 51m.
- Max allocation lifetime is 4 epochs which is ~7h 23m.
These numbers seem odd because they were set pre merge for an average block time of 13 seconds (used to be 2h and 8h).
> Update network parameters for Goerli testnet

- packages/indexer-common/package.json
Added dependency on p-map package for indexer-common. This patch resolves #495
> Fix indexer-cli docker image

- README.md
- packages/indexer-agent/README.md
- packages/indexer-agent/src/__tests__/indexer.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/indexer.ts
- packages/indexer-cli/src/__tests__/util.ts
- packages/indexer-cli/src/allocations.ts
- packages/indexer-cli/src/commands/indexer/allocations/create.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/cost-models.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/indexing-rules.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/poi-disputes.ts
- packages/indexer-common/src/indexer-management/allocations.ts
- packages/indexer-common/src/indexer-management/client.ts
- packages/indexer-common/src/indexer-management/resolvers/allocations.ts
- packages/indexer-common/src/indexer-management/subgraphs.ts
- packages/indexer-service/src/commands/start.ts
- packages/indexer-service/src/server/__tests__/server.test.ts
Remove indexer agent's assignments for subgraph deployments to specific index nodes, instead encourages the use of graph-node toml configs for flexible deployment rules. 
Currently the indexer agent and service take index-node id as provided at start-up, and round-robin the number of deployments on each node. We would like to make sure that graph node can balance deployments across available index-nodes with flexible deployment rules without conflicts from the agent. 
Resolves #504
> indexer-agent,-service: remove index-node configs

- packages/indexer-agent/src/commands/start.ts
- packages/indexer-common/src/network.ts
- packages/indexer-service/src/commands/start.ts
To support connecting to providers for any network I am updating the handling of the ethereum-network argument on startup. If ethereumNetwork name not provided the provider will use network = 'any'.  This change effectively adds support for non-standard networks with unknown names like arbitrum-goerli, etc....  The user may still specify a network name if they know it: i.e "mainnet" which provides an extra check that the provider is connecting to the correct network. 
While in there I also moved the code to connect to the network provider to a shared indexer-common function for usage by both indexer-agent and indexer-service.
> indexer-common: Support connecting to any protocol network

- packages/indexer-cli/src/actions.ts
- packages/indexer-cli/src/commands/indexer/actions/get.ts
- packages/indexer-common/src/indexer-management/actions.ts
- packages/indexer-common/src/indexer-management/client.ts
- packages/indexer-common/src/indexer-management/resolvers/actions.ts
This PRs allows the `Action` resolver to limit the number of records returned by the query.
> `indexer-cli`, `indexer-common`: Introduce the `--first` CLI option

- packages/indexer-agent/package.json
- packages/indexer-cli/package.json
- packages/indexer-service/package.json
To avoid using the package of version 0.25.x that was accidentally published in 368ffd12b6eee4eb7b65aaad9f7357e465df6eba , we define `indexer-common` and `indexer-native` to be strictly using the latest tag `0.20.5-x`
> strict versioning for indexer packages

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/indexer.ts
- packages/indexer-common/src/actions.ts
- packages/indexer-common/src/errors.ts
- packages/indexer-common/src/indexer-management/__tests__/helpers.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.ts
- packages/indexer-common/src/indexer-management/actions.ts
- packages/indexer-common/src/indexer-management/monitor.ts
- packages/indexer-common/src/indexer-management/resolvers/actions.ts
- packages/indexer-common/src/indexing-status.ts
This PR contains various improvements to code clarity and robustness. Along with some code clarity updates and an added retry loop for epoch subgraph queries, it aims to reduce noise in logs and the action queue by adding a few delays and duplicate action protections. 
- Do not add action to queue if identical action was recently successful
- Do not add action to queue if identical action failed within last 15 minutes
- Retry epoch subgraph queries
- Improve clarity of code to add offchain subgraphs to `targetDeployments`
- Improve `ActionManager.fetchActions()` and include tests for filtering on the `updatedAt` field. 
- Improve code clarity and logging on failed indexing status queries
> indexer-common,-agent: Various robustness and UX improvements

- docs/networks/testnet.md
Updating `networks.md` to reflect last week's release candidate.
> `graph-node` v0.29.0-rc.0 (testnet)

- packages/indexer-common/src/indexer-management/client.ts
Indexer common schema specification updated to be less strict - allow node to be null to account for unassigned deployments 
resolve #546 
Updated behavior example
```
Indexer Deployments
┌────────────────────────────────────────────────┬────────┬─────────┬────────────┬─────────┬─────────┬───────────────────┬──────────────────────┬─────────────────────┐
│ deployment                                     │ synced │ health  │ fatalError │ node    │ network │ latestBlockNumber │ chainHeadBlockNumber │ earliestBlockNumber │
├────────────────────────────────────────────────┼────────┼─────────┼────────────┼─────────┼─────────┼───────────────────┼──────────────────────┼─────────────────────┤
│ Qmdsp5yyFzMVUdSv5N9KndTisjXHrGDEXNaBxjyCTvDfPs │ true   │ healthy │ -          │ null    │ goerli  │ …
```
> Fix: indexer-common schema allow null node

- docs/networks/mainnet.md
- docs/networks/testnet.md
https://github.com/graphprotocol/graph-node/releases/tag/v0.29.0
> Release `graph-node` `v0.29.0` on testnet

- packages/indexer-agent/CHANGELOG.md
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-common/CHANGELOG.md
- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.ts
- packages/indexer-common/src/indexer-management/monitor.ts
- packages/indexer-common/src/indexer-management/types.ts
- packages/indexer-common/src/network.ts
- packages/indexer-service/src/commands/start.ts
- Rely on chainID from ethereum provider instead of `argv.ethereumNetwork`.
- Remove `--ethereum-network` from `indexer-agent`.
> Auto-detect `ethereum-network`

- packages/indexer-cli/package.json
- packages/indexer-cli/src/__tests__/indexer/actions.test.ts
- packages/indexer-cli/src/__tests__/references/indexer-actions.stdout
- packages/indexer-cli/src/__tests__/references/indexer-help.stdout
- packages/indexer-cli/src/actions.ts
- packages/indexer-cli/src/command-helpers.ts
- packages/indexer-cli/src/commands/indexer/actions.ts
- packages/indexer-cli/src/commands/indexer/actions/approve.ts
- packages/indexer-cli/src/commands/indexer/actions/get.ts
- packages/indexer-cli/src/commands/indexer/actions/queue.ts
- packages/indexer-cli/src/commands/indexer/actions/update.ts
- packages/indexer-cli/src/commands/indexer/allocations/reallocate.ts
- packages/indexer-common/src/actions.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.ts
- packages/indexer-common/src/indexer-management/actions.ts
- packages/indexer-common/src/indexer-management/client.ts
- packages/indexer-common/src/indexer-management/resolvers/actions.ts
This PR introduces an `actions update ...` command for updating one or more actions in the action queue. In order to support this command to update many actions in a single request an `updateActions` resolver has been added as well.
In the CLI the user can use options to filter the actions that will be updated and the user can provide key value pairs for the action keys that will be updated. 
```
graph indexer actions update [options] [<key1> <value1> ...]
```
Example usage, update all failed, reallocate actions to have force=true:
```
graph indexer actions update --status failed --type reallocate force true
```
Along with the added functionality a new test of the updateActions resolver has been included.  In a subsequent PR I'll add CLI level tests of success and failure modes for the …
> indexer-common,cli: actions update command

- packages/indexer-cli/src/__tests__/references/indexer-actions.stdout
- packages/indexer-cli/src/__tests__/references/indexer-help.stdout
- packages/indexer-cli/src/commands/indexer/actions/delete.ts
Quick update to extend the `actions delete` command to allow for deleting `all` actions or by `--status` filter
Ex.
```
graph indexer actions delete all 
graph indexer actions delete --status=queued
```
> Indexer-cli: add actions delete options

- packages/indexer-cli/src/__tests__/references/indexer-cost.stdout
- packages/indexer-cli/src/__tests__/references/indexer-help.stdout
- packages/indexer-cli/src/__tests__/references/indexer.stdout
- packages/indexer-cli/src/commands/indexer/cost/delete.ts
- packages/indexer-cli/src/cost.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/cost-models.ts
- packages/indexer-common/src/indexer-management/client.ts
- packages/indexer-common/src/indexer-management/resolvers/cost-models.ts
Add delete command for cost models
Example usage
```
./bin/graph-indexer indexer cost delete all 
./bin/graph-indexer indexer cost delete global
./bin/graph-indexer indexer cost delete Qm...
```
> indexer-common,-cli: add cost models delete

- docs/networks/mainnet.md
We're releasing `graph-node` `v0.29.0` to mainnet. Link to the release: https://github.com/graphprotocol/graph-node/releases/tag/v0.29.0.
Blockers that must be addressed before merging this PR:
The dependencies between these steps are not necessarily linear, and we might make progress on these fronts in parallel to save time.
cc @PedroMD @fordN
> Release `graph-node` `v0.29.0` on mainnet

- packages/indexer-common/src/indexer-management/types.ts
Without this extra check, a string containing a `chainId` would be handled as an alias by mistake.
> `indexer-common`: Stricter chain indentifier check on `resolveChainId`

- packages/indexer-agent/src/commands/start.ts
- packages/indexer-common/src/indexer-management/__tests__/helpers.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.ts
- packages/indexer-common/src/indexer-management/monitor.ts
- packages/indexer-common/src/indexer-management/types.ts
- packages/indexer-common/src/indexing-status.ts
- Update usage of `blockHashFromNumber()`; it expects a network alias string value for the `network` parameter.
- Update naming to improve clarity between network identifier formats (alias and id).
> indexer-common: Fix blockHashFromNumber usage

- packages/indexer-common/src/indexer-management/types.ts
This seems necessary to run the indexer-agent against a local hardhat chain.
> Add CAIP-2 entry for chain 1337

- packages/indexer-agent/config.yaml
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-service/config.yaml
- packages/indexer-service/src/commands/start.ts
- Parse --config-file and load parameters as startup arguments, include a simple default config file
- Remove deprecated yargs option: ethereum-network, vector-*
- Add network-subgraph-deployment yargs option (bug fix)
- Include network-subgraph args requirements check
- Update default config yaml, was setting a now deprecated param
- Remove vector related yargs options
> indexer-agent,indexer-service: Startup argument parsing updates and cleanup

- packages/indexer-common/src/indexer-management/types.ts
- Add the arbitrum and arbitrum-goerli chainIDs to Caip2ByChainId map
- Include `homestead` in Caip2ByChainAlias map
> indexer-common: Support arbitrum-goerli, and arbitrum

- packages/indexer-agent/CHANGELOG.md
- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-common/CHANGELOG.md
- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.ts
- packages/indexer-common/src/indexer-management/monitor.ts
- packages/indexer-common/src/indexer-management/resolvers/allocations.ts
- packages/indexer-common/src/indexer-management/types.ts
Tested on Goerli
https://testnet.thegraph.com/explorer/profile/0xa54f5494242a0c11094d76045dc01e2e544d873d?view=Indexing
> Use `EpochSubgraph` to fetch block numbers instead of `EpochManager`

- packages/indexer-service/src/queries.ts
- packages/indexer-service/src/server/index.ts
- packages/indexer-service/src/types.ts
Automated fishermen may be relying on free queries to check against untrusted indexer responses. For this purpose, they require the signal that the response is expected to be attestable.
> Forward graph-attestable header for free queries

- packages/indexer-common/src/actions.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.ts
- packages/indexer-common/src/indexer-management/allocations.ts
- packages/indexer-common/src/indexer-management/monitor.ts
- packages/indexer-common/src/indexer-management/resolvers/allocations.ts
Introduces stake feasibility check for Action batches. 
Before this, batches would be rejected even if their gross value fits in the free stake final balance.
Tasks:
> indexer-common: Implement stake feasibility check

- .github/workflows/ci.yml
- .github/workflows/publish-native-binaries.yml
- package.json
- packages/indexer-agent/package.json
- packages/indexer-cli/package.json
- packages/indexer-common/package.json
- packages/indexer-native/package.json
- packages/indexer-service/package.json
- yarn.lock
The `ci` and `publish-native-binaries` github actions use a matrix of node-versions, running the action for each version of node specified. This PR updates the node version matrix for these github actions, removing support for v13 and adding support for v17 and v18.
> github actions: Add node v17 and v18 support, remove v13

- packages/indexer-service/CHANGELOG.md
- packages/indexer-service/package.json
The `yaml` dependency was included in another package but not in indexer-service, so local builds were working but the indexer-service container did not have the necessary dependencies. This PR resolves by adding `yaml` to indexer-service dependency list.
> indexer-service: Add 'yaml' dependency

- .github/workflows/publish-native-binaries.yml
- packages/indexer-native/package.json
- yarn.lock
- Remove node v15 builds (not compatible with `lerna@6.1.0`)
- Use `actions/setup-python@v4` to specify Python version, for
compatibility with node-gyp
- Use `Ubuntu-22.04` runner for Node v18 builds
- Upgrade node-pre-gyp dependency -> `1.0.10`
> Update publish build binaries action strategies matrix

- packages/indexer-common/src/indexer-management/monitor.ts
Avoids relying on Graph Node to resolve block hashes for protocol chain blocks.  
This way, Graph Node does not need to be configured with a chain not used for indexing subgraphs.
> Use configured provider for resolving protocol chain blocks

- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.ts
- packages/indexer-common/src/indexer-management/allocations.ts
Fixes parsing of `Action.amount` during batch stake feasibility validation in the AllocationManager context.
Fixes #589
> Clean and validate `Action.amount` 

- docs/errors.md
- packages/indexer-common/src/network.ts
Early exit message on contract calls to the network
Resolve #207
> indexer-common: network pauses exit message

- packages/indexer-agent/src/agent.ts
The networkCurrentEpoch() function requires that the protocol chain be registered with the Epoch Block Oracle as an index chain. There may be cases where the protocol chain is not registered as an index chain; we don't want to block the indexer-agent reconciliation loop.
> indexer-agent: Remove networkCurrentEpoch() from critical path

- packages/indexer-common/src/indexer-management/monitor.ts
A very small move towards disambiguating error messages for bad Epoch Subgraph queries.
> common: split checks and refine error messages when querying the EBO

- packages/indexer-agent/src/commands/start.ts
- Bug fix: Collect-receipts-endpoint parser no longer "implies" `allocation-exchange-contract` since it has been deprecated (bug introduced in: https://github.com/graphprotocol/indexer/pull/598)
- Grouping: Move voucher and rebate related args to 'Query Fees' group
> indexer-agent: Fix bug in startup argument parser

- packages/indexer-common/src/indexer-management/monitor.ts
Enforces that the Epoch Subgraph is at least one epoch away from the Epoch Manager. 
Also, checks for the catastrophic case when the former is ahead of the latter.
> common: refactor epoch sync check when resolving current epoch block

- packages/indexer-common/package.json
Indexer Common requires `axios` directly, but it's not declared a dependency.
Fixes #595.
> indexer-common: Add misssing `axios` dependency

- packages/indexer-agent/src/commands/start.ts
- packages/indexer-common/CHANGELOG.md
- packages/indexer-common/src/allocations/query-fees.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.ts
To keep track of query fee metrics, add property `metrics: Metrics` to the receipt collector `AllocationReceiptCollector`, which batch receipts to collect as vouchers (exchanged through partial vouchers if needed), and redeem batched vouchers. 
Added a customized `ReceiptMetrics` property keeps track the count, success rate, and duration for basic query fee collection performances.
```
interface ReceiptMetrics {
receiptsToCollect: Gauge<'allocation'> 			// Individual receipts to collect
failedReceipts: Counter<'allocation'> 			// Failed to queue receipts to collect
partialVouchersToExchange: Gauge<'allocation'> 		// Individual partial vouchers to exchange
receiptsCollectDuration: Histogram<'allocation'> 	// Duration of processing and exchanging receipts to voucher
vouchers: …
```
> indexer-agent,-common: query fee metrics for Prometheus

- docs/networks/testnet.md
https://github.com/graphprotocol/graph-node/releases/tag/v0.30.0-rc.0
> Release graph-node `v0.30.0-rc.0` on `testnet.md`

- packages/indexer-agent/CHANGELOG.md
- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/db/migrations/11-update-deployment-names.ts
- packages/indexer-agent/src/indexer.ts
- packages/indexer-common/src/__tests__/subgraphs.ts
- packages/indexer-common/src/indexer-management/allocations.ts
- packages/indexer-common/src/indexer-management/monitor.ts
- packages/indexer-common/src/indexer-management/resolvers/allocations.ts
- packages/indexer-common/src/indexer-management/types.ts
- packages/indexer-common/src/indexing-status.ts
- packages/indexer-common/src/types.ts
When defining a deployment name, queries the Network Subgraph for the subgraph and owner names and creates a string in the form: `{subgraph}/{owner}/{ipfsHash}`.
Includes a migration that will redeploy all active subgraphs with the new name.
Fixes #574
> Detailed subgraph deployment names

- docs/action-queue.md
- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.ts
- packages/indexer-common/src/indexer-management/client.ts
Marks `reason` and `priority` fields as mandatory.
Fixes #617.
> common, docs: fix ActionInput schema

- .github/workflows/ci.yml
- packages/indexer-common/src/indexer-management/__tests__/helpers.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/cost-models.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/indexing-rules.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/poi-disputes.ts
- packages/indexer-common/src/utils.ts
- packages/indexer-service/src/server/__tests__/server.test.ts
> Introduce a configurable JSON RPC provider for tests

- packages/indexer-cli/src/__tests__/indexer/rules.test.ts
- packages/indexer-cli/src/__tests__/references/indexer-output-format.stdout
- packages/indexer-cli/src/__tests__/references/indexer-rule-deployment-yaml.stdout
- packages/indexer-cli/src/allocations.ts
- packages/indexer-cli/src/command-helpers.ts
- packages/indexer-cli/src/commands/indexer/actions/approve.ts
- packages/indexer-cli/src/commands/indexer/disputes/get.ts
- packages/indexer-cli/src/commands/indexer/rules/clear.ts
- packages/indexer-cli/src/commands/indexer/rules/delete.ts
- packages/indexer-cli/src/commands/indexer/rules/get.ts
- packages/indexer-cli/src/commands/indexer/rules/maybe.ts
- packages/indexer-cli/src/commands/indexer/rules/offchain.ts
- packages/indexer-cli/src/commands/indexer/rules/set.ts
- packages/indexer-cli/src/commands/indexer/rules/start.ts
- packages/indexer-cli/src/commands/indexer/rules/stop.ts
- packages/indexer-cli/src/commands/indexer/status.ts
- packages/indexer-cli/src/cost.ts
- packages/indexer-cli/src/disputes.ts
- packages/indexer-cli/src/rules.ts
Uncertain dependencies for toolkit's print object being passed around, avoid it by using chalk colors (is it so hard to make life colorful...?:)
resolves #468
> indexer-cli: replace gluegun toolkit print.highlight with chalk colors

- packages/indexer-agent/src/commands/start.ts
- packages/indexer-common/src/errors.ts
- packages/indexer-common/src/indexer-management/__tests__/helpers.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.ts
- packages/indexer-common/src/indexer-management/monitor.ts
- packages/indexer-common/src/indexer-management/types.ts
- packages/indexer-common/src/indexing-status.ts
> Validate Network Subgraph `chainId`

- packages/indexer-common/src/indexer-management/types.ts
Added a `Fantom` network entry to CAIP2 maps.
> indexer-common: Add support for Fantom network

- packages/indexer-service/src/server/status.ts
Update schema filter to include root fields needed by the GraphIX data comparison and debugging tool.
> indexer-service: Update index-node GraphQL server proxy schema

- docs/networks/testnet.md
Tag: https://github.com/graphprotocol/graph-node/releases/tag/v0.31.0-rc.0
> Release `v0.31.0-rc.0` to testnet

- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/cost-models.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/indexing-rules.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/poi-disputes.ts
- packages/indexer-common/src/indexer-management/allocations.ts
Remove individual action stake feasibility check in favor of the batch level check.
I've also included a few small type safety and formatting improvements suggested by my IDE.
> indexer-common: Include entire action batch in stake feasibility calculation

- packages/indexer-common/src/allocations/query-fees.ts
This PR adds a bit more context around [IE053](https://github.com/graphprotocol/indexer/blob/main/docs/errors.md#ie053) by including the action and the allocation IDs in the log message, so users can determine which action has failed.
The need for this PR arose from indexers needing clarification due to an action appearing to work despite this error being logged. Putting the `actionID` in the error context will ease investigations about such behavior, particularly in distinguishing between successful and failed actions, possibly indicating a retry.
> Include `action` and `allocation` IDs on logs for IE053

- docs/networks/mainnet.md
Proposing adding support for Fantom and Polygon to the feature support matrix. This PR will be included in the GGP (Graph Governance Proposal) to be created here https://snapshot.org/#/council.graphprotocol.eth.
This PR should be merged after Council approval. Afterward, the reference to the canonical GGP-ratified feature support matrix (end of the .md) will be updated.
> Update feature support matrix to include Fantom and Polygon

- packages/indexer-common/src/indexer-management/types.ts
Switch cip2 chain-id mapping for `polygon` to `matic`
> indexer-common: update polygon network name to matic

- docs/networks.md
- docs/networks/arbitrum-goerli.md
- docs/networks/arbitrum-one.md
- docs/networks/ethereum-goerli.md
- docs/networks/ethereum-mainnet.md
- docs/networks/testnet.md
**What changed:**
- renamed mainnet.md -> ethereum-mainnet.md
- renamed testnet.md -> ethereum-goerli.md
- bumped indexer stack versions
- use hosted service urls for the network subgraphs
**What's been added:**
- added arbitrum-one.md
- added arbitrum-goerli.md
**What's missing:**
- arbitrum one and goerli network subgraph IPFS hash
- arbitrum one and goerli Data Edge and Block Oracle Owner contract addresses
- arbitrum one and goerli DAI contract address
> update networks docs

- docs/feature-support-matrix.md
- docs/networks/arbitrum-goerli.md
- docs/networks/arbitrum-one.md
- docs/networks/ethereum-goerli.md
- docs/networks/ethereum-mainnet.md
Still a draft PR because we're waiting for GGP approval.
EDIT 2023-06-23: now ready for review.
> Release Graph Node `v0.31.0` on mainnet

- packages/indexer-agent/src/agent.ts
- packages/indexer-common/src/indexer-management/monitor.ts
- packages/indexer-common/src/types.ts
Major changes:
- Refactor NetworkSubgraph query for transferred subgraphs, considering some fields will always be `null` on L1.
- For synced subgraph deployments and during the first 48 hours after the transfer started: 
- On **L1**: Keep allocations open
- On **L2**: Open allocations and create a `decisionBasis=always` indexing rule. *(Indexers are expected to manually update this rule afterwards)*
This means transfers older than 48h will be ignored by this feature.
Minor changes:
- auto-formatting 
- use of `networkIsL1` and `networkIsL2` helper functions
> Refactor: Auto L2 Transfer Support

- .github/workflows/check-formatting.yml
- .github/workflows/ci.yml
- packages/indexer-agent/src/__tests__/indexer.ts
- packages/indexer-cli/src/__tests__/util.ts
- packages/indexer-common/package.json
- packages/indexer-common/src/allocations/query-fees.ts
- packages/indexer-common/src/indexer-management/__tests__/allocations.test.ts
- packages/indexer-common/src/indexer-management/__tests__/helpers.test.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/cost-models.test.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/indexing-rules.test.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/poi-disputes.test.ts
- packages/indexer-common/src/indexer-management/__tests__/util.ts
- packages/indexer-common/src/indexer-management/actions.ts
- packages/indexer-service/src/server/__tests__/server.test.ts
This fix adds error handling to the two timers that periodically query
the database: one which gets actions from the queue, and other that gets pending
vouchers. In tests, the DB tables are dropped, so the timers would throw
errors and cause tests to fail. In production whatever errors cause
a DB fetch to fail could be recoverable so the timer will keep retrying
rather than bubbling up an exception, so hopefully that is okay.
We also change CI to only build using Ubuntu 22.04
(the node 18 version has dependency issues on Ubuntu 20.04) and on
node 16 and 18 (the node 17 version was failing to download node, and is EOL).
Additionally we make CI tests and formatting check happen on all PRs, not
only the ones to main.
> fix: handle errors fetching actions and vouchers from the DB 

- docs/feature-support-matrix.md
- docs/networks.md
- docs/networks/arbitrum-one.md
- docs/networks/ethereum-mainnet.md
I also removed the feature support matrix from Ethereum mainnet & Arbitrum One environments, as we've agreed it should be the same on environments.
Another GGP will be created in https://snapshot.org/#/council.graphprotocol.eth referencing the latest feature support matrix. After Council approval, this PR should be merged.
> Updated feature support matrix to support indexing rewards for substreams 

- .github/workflows/publish-native-binaries.yml
github runners no longer support v18.04 ubuntu LTS, the oldest release is 20.04 LTS
> Update ci ubuntu OS version

- packages/indexer-common/src/indexer-management/actions.ts
- packages/indexer-common/src/operator.ts
The second expression of the conditional was blocking the error handling.
> Fix error handling for recently executed actions

- packages/indexer-common/src/network.ts
Indexer registration was happening regardless of the indexer being detected on chain.
> agent: Fix indexer registration

- packages/indexer-common/src/__tests__/network-specification-files/invalid-address.yml
- packages/indexer-common/src/__tests__/network-specification.test.ts
- packages/indexer-common/src/network-specification.ts
Our input validation framework does not catch errors when converting values to the `Address` type. This PR adds a check to ensure that the provided value is a valid `Address` before attempting the conversion.
> More helpful error messages for address validation

- packages/indexer-agent/src/agent.ts
Setting allocation decisions to false would try to close allocations when on manual mode. It wouldn't actually go through because actions won't really be queued on manual, thankfully.
This PR changes it so that we use an empty array of allocation decisions for the network that is in manual mode, making the reconcile step a noop instead of an attempt to close all allocations.
> fix: properly skip reconciling allocations on a network in manual mode

- packages/indexer-common/src/allocations/query-fees.ts
- packages/indexer-service/src/query-fees/allocations.ts
The `allocation_summary` row is saved without a reference to the current `transaction` object.
Since the transaction's isolation level is set to [`REPEATABLE_READ`](https://www.postgresql.org/docs/current/transaction-iso.html#XACT-REPEATABLE-READ), it is possible that the new allocation summary is not visible to the subsequent insertion into `allocation_summaries`, which is scoped to the ongoing transaction.
> Indexer-Service: save `allocation_summary` within transaction

- packages/indexer-agent/src/db/migrations/11-add-protocol-network-field.ts
Constraint name was being created as a literal string.
No data is in risk, but the constraint name must be corrected.
> Fix string interpolation in migration file

- docs/networks/arbitrum-goerli.md
- docs/networks/arbitrum-one.md
- docs/networks/ethereum-goerli.md
- docs/networks/ethereum-mainnet.md
Latest deployments taken from the NO IPFS canonical endpoints:
* Mainnet: https://thegraph.com/hosted-service/subgraph/graphprotocol/no-ipfs-network-ethereum?version=pending
* Arbitrum-one: https://thegraph.com/hosted-service/subgraph/graphprotocol/no-ipfs-network-arbitrum?version=pending
* Goerli: https://thegraph.com/hosted-service/subgraph/graphprotocol/no-ipfs-network-goerli?version=pending
* Arbitrum-Goerli: https://thegraph.com/hosted-service/subgraph/graphprotocol/no-ipfs-network-arb-goerli?version=pending
> chore: update all networks docs to the latest NO IPFS release

- packages/indexer-cli/src/commands/indexer/actions/get.ts
- packages/indexer-cli/src/commands/indexer/actions/queue.ts
- packages/indexer-cli/src/commands/indexer/allocations/close.ts
- packages/indexer-cli/src/commands/indexer/allocations/create.ts
- packages/indexer-cli/src/commands/indexer/allocations/get.ts
- packages/indexer-cli/src/commands/indexer/allocations/reallocate.ts
- packages/indexer-cli/src/commands/indexer/disputes/get.ts
- packages/indexer-cli/src/commands/indexer/rules/clear.ts
- packages/indexer-cli/src/commands/indexer/rules/delete.ts
- packages/indexer-cli/src/commands/indexer/rules/get.ts
- packages/indexer-cli/src/commands/indexer/rules/maybe.ts
- packages/indexer-cli/src/commands/indexer/rules/set.ts
- packages/indexer-cli/src/commands/indexer/rules/start.ts
- packages/indexer-cli/src/commands/indexer/rules/stop.ts
- packages/indexer-cli/src/commands/indexer/status.ts
Adds the supported network names in `indexer-cli` command's usage texts.
When `--network` is passed as an option:
```shellsession
$ ./graph-indexer indexer actions queue --help
💁
graph indexer actions queue [options] <ActionType> <targetDeployment> <param1> <param2> <param3> <param4>
graph indexer actions queue [options] allocate <deploymentID> <amount>
graph indexer actions queue [options] unallocate <deploymentID> <allocationID> <poi> <force>
graph indexer actions queue [options] reallocate <deploymentID> <allocationID> <amount> <poi> <force>
Options:
-h, --help                    Show usage informatio
-n, --network <STRING>        [Required] The protocol network for this action (mainnet, arbitrum-one, goerli, arbitrum-goerli)
-o, --output table|json|yaml  Choose the output format: …
```
> Display supported networks in indexer-cli usage text

- packages/indexer-agent/CHANGELOG.md
- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/cost.ts
- packages/indexer-agent/src/index.ts
- packages/indexer-agent/src/syncing-server.ts
- packages/indexer-common/src/allocations/query-fees.ts
- packages/indexer-common/src/network.ts
- packages/indexer-common/src/transactions.ts
- packages/indexer-service/src/commands/start.ts
Adds `await` before `async` function calls.
- Fixes network subgraph deployments being removed right after they are synced.
- Add logs inside `reconcileDeployment` function.
> Fix floating promises

- docs/feature-support-matrix.md
There is a new Graph Node pre-release [v0.32.0-rc.0](https://github.com/graphprotocol/graph-node/releases/tag/v0.32.0-rc.0). 
As per usual, A GGP (Graph Governance Proposal) will be created as a [snapshot vote](https://snapshot.org/#/council.graphprotocol.eth) for Council approval. Once ratified, Graph Node v0.32.0 will be released for mainnet adoption and this PR will be merged.
> Update feature-support-matrix.md w/ Graph Node v0.32.0 as minimum version

- packages/indexer-agent/src/agent.ts
- packages/indexer-service/CHANGELOG.md
- packages/indexer-service/src/commands/start.ts
Emit warnings instead of throwing an error, which is causing the process to exit.
> Relax network subgraph validation in Indexer Service startup

- packages/indexer-common/CHANGELOG.md
- packages/indexer-common/src/indexer-management/resolvers/poi-disputes.ts
- packages/indexer-common/src/operator.ts
Besides that, fix a duplicate log message.
> Reference conflict targets when upserting POIDisputes

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/commands/common-options.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-common/src/types.ts
Resolves https://github.com/graphprotocol/indexer/issues/713
> Auto and Manual deployment management modes

- docs/networks/arbitrum-goerli.md
- docs/networks/arbitrum-one.md
- docs/networks/ethereum-goerli.md
- docs/networks/ethereum-mainnet.md
These are the new subgraph deployment id's corresponding to the exponential rebates ugprade.
> chore: update network subgraph deployment ids

- packages/indexer-cli/src/commands/indexer/actions/approve.ts
> cli: add a --network option for the actions approve command

- packages/indexer-common/src/indexer-management/allocations.ts
Multiple actions are executed in a single transaction using the multicall paradigm, so the call data for each action is prepared and then combined into a single transaction. The call data for each action in the batch are prepared concurrently for efficiency; however, there was some innefficiencies in the concurrent preparation of call data due to redundancy in data used between the functions and a naive approach being used to validate that a deployment is healthy.
Instead of refetching the same data during the preparation step for each and every action in the batch let's just fetch the data once and share it across all of them. To do this I've created a new context interface: 
```typescript
export interface TransactionPreparationContext {
activeAllocations: Allocation[]
currentEpoch: …
```
> indexer-agent: Improve batch action preparation

- packages/indexer-common/src/errors.ts
- packages/indexer-common/src/network-subgraph.ts
- packages/indexer-service/src/allocations.ts
- packages/indexer-service/src/commands/start.ts
- Remove freshness checker from network subgraph (i.e don't wait for subgraph to be within chain head just use what we have).
- Add validation of operator wallet configs on startup.
> indexer-service: Various robustness improvements

- packages/indexer-agent/src/cost.ts
- Add fallback if decimals() call to DAI contract fails (default to 18)
> indexer-agent: Improve robustness of DAI contract contract calls

- docs/networks/arbitrum-sepolia.md
- docs/networks/config-examples/arbitrum-sepolia-indexer-agent-config.yaml
- docs/networks/config-examples/sepolia-indexer-agent-config.yaml
- docs/networks/ethereum-sepolia.md
Adding network.md files for the new Testnet protocol instances.
> docs/networks: Add network config docs for Sepolia and Arbitrum Sepolia

- packages/indexer-agent/src/__tests__/agent.ts
- packages/indexer-agent/src/agent.ts
This PR refactors a small portion of the Reconciliation Loop for easier testing.
> agent: add tests for allocation decision consolidation

- docs/networks/arbitrum-goerli.md
- docs/networks/arbitrum-one.md
I got a bit confused by this documentation when I was working on L2 migration. That's why I would like to make this more clear for everyone else.
> docs/networks: Arbitrum and Arbitrum Goerli update

- packages/indexer-service/src/commands/start.ts
Handle case where indexer does not use an operator wallet; they are free to use the same wallet as their main indexer address (though not recommended).
> indexer-service: Improve validation of operator wallet

- packages/indexer-common/src/actions.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.test.ts
- packages/indexer-common/src/indexer-management/__tests__/util.ts
- packages/indexer-common/src/indexer-management/resolvers/actions.ts
- Remove the check that confirms the deployment is already published to the network; to avoid race conditions waiting for the network subgraph to update. In the case that the deployment cannot be found on the network emit a warning and continue.
> common: Reduce stringency of action validation when adding to queue

- packages/indexer-service/src/server/status.ts
The graph-node is exposing the version information using the following struct, however, it's not exposed through the indexer-service status endpoint. 
This PR adds that information so that the gateway can have access to it.
```
struct Version {
version: String,
commit: String,
}
```
> feat(indexer-service): Add graph-node version endpoint from status api

- package.json
- packages/indexer-native/lib/index.test.js
- yarn.lock
- To be upgraded again once Dockerfile and workflows are upgraded. Version lerna@8.0.2 was not compatible with Node v16.
> *: Downgrade lerna dependency

- packages/indexer-agent/src/commands/start.ts
- packages/indexer-common/src/network-specification.ts
- packages/indexer-common/src/network.ts
- packages/indexer-service/src/commands/start.ts
depends on https://github.com/graphprotocol/common-ts/pull/114
> feat: optionally override address book

- packages/indexer-agent/src/commands/start-multi-network.ts
when trying to run locally for some reason `yargs` doesn't show me `dir` as a parsed arg, I would expect it to create aliases automatically so we can reference it. But adding this as safe guards for anyone it doesn't work.
> agent: if alias does not exist try the actual flag

- packages/indexer-agent/src/agent.ts
- packages/indexer-common/src/indexer-management/allocations.ts
- Allow indexers to control the subgraph deployment safety check: 
- Set `indexingRule.safety = true` to turn on the deployment health check. The agent will _not_ allocate to the deployment if it has `health = failed`.
- Set `indexingRule.safety = false or null` to turn off the deployment health check. The agent will still allocate to  subgraph deployments with `health = failed`.
- Move the deployment health check to earlier in the decision process, within `reconcileDeploymentAllocationAction()`.  This gives the check access to the indexingRule so it can use the `safety` property, it also is useful to prevent action from being added to the queue in the first place. In the previous/current setup the action does not included in a transaction but it will remain in the queue and continue to …
> agent,common: Improve control of subgraph deployment health safety check

- docs/feature-support-matrix.md
Updated the Feature Matrix Support with the recommended minimum Graph Node version version [v0.34.1](https://github.com/graphprotocol/graph-node/releases/tag/untagged-d207d57ec36b1c1623ac).
Next steps:
1. @PedroMD creates the GGP (Graph Governance Proposal) referencing this PR (https://snapshot.org/#/council.graphprotocol.eth).
2. Council votes on the proposal, ratifying the latest Feature Matrix Support.
3. @PedroMD adds the proposal link to the matrix and merges this PR.
> Docs: updated feature support matrix with Graph Node v0.34.1

- packages/indexer-service/src/allocations.ts
Previously, the indexer-service would fail to handle queries if it had more than 1000 active allocations.
> fix: paginate allocation queries

- Dockerfile.indexer-agent
The PR increases the memory limit for nodejs in the indexer-agent to fix it from crashing for upgrade indexer.
> increase memory limit for node-js

- packages/indexer-agent/src/__tests__/indexer.ts
- packages/indexer-common/src/indexer-management/__tests__/allocations.test.ts
- packages/indexer-common/src/indexer-management/__tests__/helpers.test.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.test.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/indexing-rules.test.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/poi-disputes.test.ts
- packages/indexer-common/src/indexer-management/__tests__/util.ts
- packages/indexer-common/src/indexer-management/types.ts
- packages/indexer-common/src/parsers/__tests__/parsers.ts
- packages/indexer-service/src/server/__tests__/server.test.ts
locally I had issues running the tests. It turned out we were still using `goerli` which is deprecated now so updating the test RPC to sepolia
> chore: use sepolia instead of goerli for tests

- packages/indexer-common/src/indexer-management/__tests__/helpers.test.ts
- packages/indexer-common/src/indexer-management/actions.ts
- packages/indexer-common/src/indexer-management/resolvers/actions.ts
I noticed that the existing actions that the new actions are compared against to check for duplicates are queried outside the Sequelize transaction that will eventually write the action to the db. We've noticed that duplicates happen when two actions are added to the database in quick succession (<2s). By performing both the existing action queries and the database write within the same transaction, this hopefully won't happen any more.
This hopefully fixes duplicate actions being added to the queue (#879).
> Avoid race conditions when queuing actions (hopefully fixes #879)

- docs/feature-support-matrix.md
- Updates the supported Graph Node version to [0.35.0](https://github.com/graphprotocol/graph-node/releases/tag/v0.35.0)
- Adds support for Arweave File Data Sources (at same level as IPFS, given identical implementation and data isolation), supported as of Graph Node [0.33.0](https://github.com/graphprotocol/graph-node/releases/tag/v0.33.0)
- Adds support for ENS (as of [0.32.0](https://github.com/graphprotocol/graph-node/releases/tag/v0.32.0), this functionality was undeprecated, as the failure in the absence of the table was non-deterministic, until indexers import the [ENS rainbow tables](https://github.com/graphprotocol/ens-rainbow))
TODO: create and link to GGP
> Update feature support (ens, arweave, 0.35.x)

- docs/networks/arbitrum-one.md
- docs/networks/arbitrum-sepolia.md
- docs/networks/ethereum-mainnet.md
- docs/networks/ethereum-sepolia.md
Updated with latest deployment hashes
Can be double checked on their respective endpoints on hosted service
> chore: update network subgraph deployment hashes

- docs/feature-support-matrix.md
Adds full protocol support for base, bsc, scroll, and linea as data sources. The Council has already reviewed the CIP (Chain Integration Process) reports, and support for these chains was already verbally voted on.
Next steps:
> docs: added base, bsc, scroll and linea to the feature support matrix

- packages/indexer-service/jest.config.js
- packages/indexer-service/package.json
- packages/indexer-service/src/server/__tests__/server.test.ts
- Fix server tests
- Add request/response tests for following paths: /operator/info, /subgraphs/health/, /cost, /status
> Indexer-service: Server integration tests

- packages/indexer-agent/src/commands/start.ts
- packages/indexer-cli/src/__tests__/cli.test.ts
- packages/indexer-cli/src/__tests__/indexer/actions.test.ts
- packages/indexer-cli/src/__tests__/indexer/cost.test.ts
- packages/indexer-cli/src/__tests__/indexer/rules.test.ts
- packages/indexer-cli/src/__tests__/references/indexer-cost-model-deployment-multinetworks.stdout
- packages/indexer-cli/src/__tests__/references/indexer-cost-variables-deployment-multinetworks.stdout
- packages/indexer-cli/src/__tests__/util.ts
- packages/indexer-common/src/indexer-management/client.ts
- packages/indexer-common/src/indexer-management/resolvers/cost-models.ts
- `multiNetworks` was erroneously typed as possibly `undefined`, and `undefined` was used as a way to determine if we are in multi or single network mode in `cost-models.ts`.
However, the code doesn't actually allow for `multiNetworks` to be undefined, be it in multi or single network mode.
- The inject DAI setting now defaults to false
- Cost models are allowed only *if in single network mode* and:
- On Ethereum mainnet
- On any other network **and** "inject DAI" off
Some of these changes should be inconsequential considering the impending deprecation of Ethereum mainnet, as well as the fact that most indexers stopped using cost models due in part to #789.
Fixes #789
> Allow cost models in single network mode

- packages/indexer-common/src/indexer-management/__tests__/helpers.test.ts
- packages/indexer-common/src/indexer-management/monitor.ts
- Update several `NetworkMonitor` functions to paginate by `id` instead of by `createdAt`. Functions updated: subgraphs(), subgraphDeployments() and disputableAllocations(). 
On L2 networks, like arbitrum-one, `createdAt` is not necessarily unique, so paginating based on `createdAt` can lead to missing items.
> indexer-common: Avoid using createdAt field for pagination

- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/tsconfig.json
- packages/indexer-common/src/parsers/index.ts
- Properly exported error-handling module.
- Removed tsconfig workaround.
`error-handling` is not being properly exported for use in other packages where it's now used.
```
Error: Cannot find module '@graphprotocol/indexer-common/src/parsers/error-handling'
Require stack:
- /opt/indexer/packages/indexer-agent/dist/commands/start.js
- /opt/indexer/packages/indexer-agent/dist/index.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
at Module._load (node:internal/modules/cjs/loader:985:27)
at Module.require (node:internal/modules/cjs/loader:1235:19)
at require (node:internal/modules/helpers:176:18)
at Object.<anonymous> (/opt/indexer/packages/indexer-agent/dist/commands/start.js:18:26)
at Module._compile (node:internal/modules/cjs/loader:1376:14)
at …
```
> common,agent: fix tsconfig, error-handling export

- packages/indexer-common/src/indexer-management/__tests__/util.ts
In release 0.23.1, some are encountering a type annotation issue building cli.
```
src/indexer-management/__tests__/util.ts(19,14): error TS2742: The inferred type of 'testNetworkSpecification' cannot be named without a reference to '@graphprotocol/indexer-cli/node_modules/ethers'. This is likely not portable. A type annotation is necessary.
```
> indexer-cli: add type annotation for test util network specification

- package.json
Using [corepack](https://nodejs.org/api/packages.html#packagemanager) so it is easier to manage pacakge manager used in the project.
> chore: add package manager for corepack to detect

- packages/indexer-agent/src/__tests__/indexer.ts
- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/commands/common-options.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-cli/src/__tests__/util.ts
- packages/indexer-common/src/allocations/__tests__/tap.test.ts
- packages/indexer-common/src/graph-node.ts
- packages/indexer-common/src/indexer-management/__tests__/allocations.test.ts
- packages/indexer-common/src/indexer-management/__tests__/helpers.test.ts
- packages/indexer-common/src/indexer-management/__tests__/util.ts
- packages/indexer-common/src/indexer-management/client.ts
- packages/indexer-service/src/commands/start.ts
- packages/indexer-service/src/server/__tests__/server.test.ts
[Hands off the assignments](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbTd2ZHhyenNxd29sYjE3aWdxNWFxbDVrb3R5azF5bXBybWYyMDd2bSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/jtKYsTf4BtrzzaMfMT/giphy.gif)
Resolve #853 
- Use recently added subgraph_pause method to explicitly pause subgraph deployments rather than virtually pausing them by assigning to a non-existent index node
- Remove index-node-ids startup parameter from indexer-agent
- Never send an index-node-id param with subgraph_deploy requests, the receiving graph-node will make the index-node-id decision based on the graph-node.toml config file
> indexer-agent: Leave subgraph deployment assignment decisions to graph-node

- packages/indexer-agent/src/__tests__/indexer.ts
- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/commands/common-options.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/db/migrations/14-use-new-deployment-pause-mechanism.ts
- packages/indexer-cli/src/__tests__/util.ts
- packages/indexer-common/src/allocations/__tests__/tap.test.ts
- packages/indexer-common/src/allocations/monitor.ts
- packages/indexer-common/src/errors.ts
- packages/indexer-common/src/graph-node.ts
- packages/indexer-common/src/indexer-management/__tests__/allocations.test.ts
- packages/indexer-common/src/indexer-management/__tests__/helpers.test.ts
- packages/indexer-common/src/indexer-management/__tests__/util.ts
- packages/indexer-common/src/indexer-management/allocations.ts
- packages/indexer-common/src/indexer-management/client.ts
- packages/indexer-service/src/commands/start.ts
- packages/indexer-service/src/server/__tests__/server.test.ts
Graph-node recently added support for explicit pausing of subgraph deployments (in the past they were paused virtually by assigning the deployment to a nonexistent node). 
This PR adds a migration that interacts with the Graph Node indexingStatuses query and JSON-RPC server to update all virtually paused deployments (node = 'removed') to use the new explicit pausing mechanism. It also updates the process of deploying subgraphs, the indexer-agent will no longer specify the index node to which the deployment is assigned; instead the graph-node makes the assignment decisions. 
- Migrate subgraph deployment assignments to use explicit pause mechanism
- Use recently added subgraph_pause method to explicitly pause subgraph deployments rather than virtually pausing them by assigning to a …
> agent,common: Migrate subgraph deployment assignments to use explicit 'paused' mechanism

- docs/networks/arbitrum-one.md
- docs/networks/arbitrum-sepolia.md
- docs/networks/ethereum-mainnet.md
- docs/networks/ethereum-sepolia.md
- Remove reference to --ethereum-network param (no longer used)
- Update gateway endpoint params, now use a single url and use that to build the paths (such as /collect-receipts)
> Network Docs: Remove reference to deprecated ethereum-network param, update gateway params

- packages/indexer-common/src/transactions.ts
- Improve attempt count comparison
- Improve logging of BigNumber gas price and gas fee values
HT to @chriswessels for these changes which were pulled almost wholesale from https://github.com/graphprotocol/indexer/pull/392
> common: Improve gas fee and price logging in TransactionManager

- docs/subgraph-freshness.md
- packages/indexer-common/src/network-specification.ts
The default values were far too strict, leading to the agent operations halting.
- Update default `maxBlockDistance`:  0 --> 1000.
- Update default `freshnessSleepMilliseconds`: 5,000 --> 10,000
- Update subgraph-freshness feature docs to reflect change in defaults.
> common, docs: Update subgraph maxBlockDistance default values

- packages/indexer-agent/src/commands/start.ts
- packages/indexer-common/src/allocations/__tests__/tap.test.ts
- packages/indexer-common/src/allocations/query-fees.ts
- packages/indexer-common/src/network.ts
Regarding issue #946 
Instead of passing along a reference better to just use the sequelize reference inside the model object
> fix: remove queryInterface reference

- packages/indexer-cli/src/__tests__/references/indexer-help.stdout
- packages/indexer-cli/src/allocations.ts
- packages/indexer-cli/src/commands/indexer/allocations/collect.ts
- packages/indexer-common/src/indexer-management/client.ts
- packages/indexer-common/src/indexer-management/resolvers/allocations.ts
- indexer-common: Add `submitCollectReceiptsJob` graphQL resolver for kicking off receipt collection
- indexer-cli: Add helper function for sending mutation to the `submitCollectReceiptsJob` resolver
- indexer-cli: Add `collect` command to `allocations` module that uses the new helper and graphQL resolver to submit a job to collect receipts for an allocation
> indexer-cli, indexer-common: Add CLI command to kick off receipt collection for an allocation

- packages/indexer-common/src/graph-node.ts
The `paused` field is optional.
> common: Fix handling of indexingStatus responses from graph-node

- packages/indexer-common/src/graph-node.ts
- Subgraph deployment is active when `node != removed`.
> common: Fix filtering when fetching active subgraphs

- .github/workflows/publish-native-binaries.yml
- package.json
- packages/indexer-native/lib/index.js
- packages/indexer-native/lib/index.test.js
- packages/indexer-native/native/Cargo.lock
- packages/indexer-native/native/Cargo.toml
- packages/indexer-native/native/build.rs
- packages/indexer-native/native/src/attestation.rs
- packages/indexer-native/native/src/lib.rs
- packages/indexer-native/native/src/signature_verification.rs
- packages/indexer-native/package.json
- packages/indexer-service/package.json
In working to resolve https://github.com/graphprotocol/indexer/issues/972, I pulled in some changes from https://github.com/graphprotocol/indexer/pull/749, while retaining our prebuilt pipeline.
> fix(indexer-native): neon 1.0.0, napi-6

- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/types.ts
Indexers should be able to control the frequency of data polling and decision making depending on their business strategy and backend saturation.
- Add startup parameter for configuring data collection polling intervals, `--polling-interval`. 
- Make polling intervals (Eventuals timers) more consistent.
The polling interval sets the request intervals for data as follows:
`pollingInterval` defaults to 120_000 ms (2 minutes).
- **indexingRules**:
- **interval**: pollingInterval
- **source**: indexer DB
- **activeDeployments**:
- **interval**: pollingInterval
- **source**: graph-node
- **networkDeployments**:
- **interval**: pollingInterval
- **source**: network subgraph
- **activeAllocations**:
- **interval**: pollingInterval
- **source**: network subgraph
- **eligibleTransferDeployments**: …
> agent: Allow configuring polling interval for data collection

- packages/indexer-common/src/epoch-subgraph.ts
- packages/indexer-common/src/graph-node.ts
- packages/indexer-common/src/network-subgraph.ts
- packages/indexer-common/src/subgraphs.ts
Today indexers do not have a way to know what subgraph is "not fresh" this PR aims to introduce the `endpoint` of subgraph we consider is "not fresh" in the freshness checker
closes https://github.com/graphprotocol/indexer/issues/803
> common: log endpoint in freshness checker

- packages/indexer-common/src/graph-node.ts
Resolves an issue where graph-node returns an error when querying deployment assignment statuses and the `paused` value is null. 
https://github.com/graphprotocol/graph-node/issues/5550
> agent: defend against graph-node bug #5550 (null paused)

- packages/indexer-common/src/indexer-management/allocations.ts
Recreating #983 for @datanexus-vincent so CI can run on this.
> common: Remove failed subgraph check

- packages/indexer-common/src/graph-node.ts
Corrects the query responsible for checking the graph-node indexingStatus.
> indexer-common: fix paused mechanism

- packages/indexer-agent/src/db/migrations/12-add-scalar-tap-table.ts
- packages/indexer-agent/src/db/migrations/15-modify-scalar-tap-tables.ts
Migrations from the [indexer-rs](https://github.com/graphprotocol/indexer-rs/blob/ead4ac2afa4de1740de0eb395cb8168ef2b8a74b/migrations/20230912220523_tap_receipts.up.sql#L9-L10) side are using the correct value at `scalar_tap_ravs > value_aggregate` since it uses unsigned 128bits numbers (39 digits)
We had at first in mind 64 (therefore the 20 digits) but we need to increase this to match indexer-rs
This also happens for the [nonce](https://github.com/graphprotocol/indexer-rs/blob/ead4ac2afa4de1740de0eb395cb8168ef2b8a74b/migrations/20230912220523_tap_receipts.up.sql#L9-L10) where it is defined as 20 digits so we are specifying it in the migrations
After running this new migrations its necessary to restart  TAP-AGENT
> agent: fix db migration for value_aggregate from 20 to 39 digits

- packages/indexer-common/src/indexer-management/types.ts
- Add `moonbeam`, `fuse`, and `blast`  to chain id lookups. (in preparation for https://github.com/graphprotocol/indexer/pull/979)
> common: add moonbeam, fuse, blast to chain id lookups 

- packages/indexer-agent/src/db/migrations/14-use-new-deployment-pause-mechanism.ts
- Update migration 14 to only effect subgraphs assigned to node = 'removed'
> indexer-agent: Improve DB migration 14  which migrates deployments to use pause mechanism

- packages/indexer-service/src/allocations.ts
Removes the limit on the LRU cache. This should prevent request times from spiking and we'll see any issues in instance RAM utilization instead.
> indexer-service: remove LRU max length

- packages/indexer-common/src/allocations/__tests__/tap.test.ts
- packages/indexer-common/src/allocations/query-fees.ts
> fix: use subgraph timestamp for tap

- packages/indexer-common/src/indexer-management/__tests__/allocations.test.ts
Disables the stakeUsageSummary test, as it's relying on an allocation which is not producing rewards anymore.
> fix: disable stakeUsageSummary test

- packages/indexer-agent/src/db/migrations/14-cost-models-history.ts
- packages/indexer-common/src/indexer-management/models/cost-model.ts
- packages/indexer-common/src/indexer-management/resolvers/cost-models.ts
Reason for this PR. 
tl;dr: needed for TAP cost model checks
We currently have an issue where when a cost model just got updated  the indexer-service takes some time to update but in the meantime it errors out due to the model not matching, so we need to have a history in the db so that we can accept both, the new and the old one for a delimited amount of time (eg. ~2min)
This PR includes a breaking change:
- CostModels table no longer exists
- cost_models table is created, this will contain a history of all past cost models
- CostModels table will keep working as a view from cost_models this way other programs that read into CostModels will keep working as they are, this view will contain only the latest model of each deployment thus not breaking anything else
> feat: add history for cost models and set view table for latest models

- packages/indexer-agent/src/db/migrations/16-modify-invalid-receipts-table.ts
- packages/indexer-common/src/query-fees/models.ts
Added new column to keep track of why each invalid receipt failed, for easier future debbuging
> feat: Add new column to invalid_receipts table

- docs/feature-support-matrix.md
Adds full protocol support for ~`moonbeam`,~ `fuse`, and `blast` data sources. 
The Council will be reviewing the CIP reports for these chains this Thursday. 
Next steps:
EDIT: removed `moonbeam` from the list.
> docs: Add 2 chains to feature matrix: fuse & blast

- packages/indexer-common/src/allocations/__tests__/tap-pagination.test.ts
- packages/indexer-common/src/allocations/__tests__/tap.test.ts
- packages/indexer-common/src/allocations/__tests__/validate-queries.test.ts
- packages/indexer-common/src/allocations/tap-collector.ts
- packages/indexer-common/src/indexer-management/__tests__/helpers.test.ts
- packages/indexer-common/src/network.ts
- packages/indexer-common/src/tap-subgraph.ts
> fix: add pagination to tap collector

- packages/indexer-common/src/allocations/__tests__/escrow-accounts.test.ts
- packages/indexer-common/src/allocations/__tests__/tap.test.ts
- packages/indexer-common/src/allocations/escrow-accounts.ts
- packages/indexer-common/src/allocations/index.ts
- packages/indexer-common/src/allocations/tap-collector.ts
> feat: check escrow balance before rav redeem

- packages/indexer-agent/CHANGELOG.md
- packages/indexer-agent/package.json
- packages/indexer-agent/src/commands/common-options.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-cli/CHANGELOG.md
- packages/indexer-cli/package.json
- packages/indexer-common/CHANGELOG.md
- packages/indexer-common/package.json
- packages/indexer-native/CHANGELOG.md
- packages/indexer-native/package.json
- packages/indexer-service/CHANGELOG.md
- packages/indexer-service/package.json
- packages/indexer-service/src/commands/start.ts
- yarn.lock
Moving #1038 to the main fork, also squashed and reworded to match our commit guidelines.
> all: allow db ssl if configured (default: unchanged)

- docs/networks/arbitrum-sepolia.md
- lerna.json
- packages/indexer-agent/package.json
- packages/indexer-agent/src/db/migrations/14-use-new-deployment-pause-mechanism.ts
- packages/indexer-cli/package.json
- packages/indexer-common/package.json
- packages/indexer-service/package.json
> all: release-0.21.7 bump, paused migration fix

- packages/indexer-agent/src/commands/common-options.ts
- packages/indexer-agent/src/commands/start.ts
- Move polling-interval args option to common-options so it is set/used in both single-network and multi-network modes.  This fixes its usage in multi-network mode, previously it was being read in as undefined which leads to it being parsed as a 0 number, so the polling loop was going crazy with a 0 polling interval.
> agent: Fix polling-interval arg setting

- docs/feature-support-matrix.md
- packages/indexer-common/src/indexer-management/types.ts
Common:
- Adds `boba`, `boba-bnb`, and `blast-mainnet` to chain id lookups. A bug was introduced in https://github.com/graphprotocol/indexer/pull/980 and https://github.com/graphprotocol/indexer/pull/979 when adding `blast` instead of `blast-mainnet` as the slug currently used in Subgraph Studio and Graph Explorer. 
Docs: 
- Same network names as above were added & removed from the feature matrix.
Next steps:
> docs & common: add support for boba, boba-bnb and fix for blast

- packages/indexer-common/src/allocations/__tests__/tap-pagination.test.ts
- packages/indexer-common/src/allocations/__tests__/tap.test.ts
- packages/indexer-common/src/allocations/__tests__/validate-queries.test.ts
- packages/indexer-common/src/indexer-management/__tests__/allocations.test.ts
- packages/indexer-common/src/indexer-management/__tests__/helpers.test.ts
- packages/indexer-common/src/indexer-management/__tests__/resolvers/actions.test.ts
For now, disabling tests that make RPC calls which are blocking up CI anytime that fails.
> common: skip tests that make rpc calls

- packages/indexer-common/src/indexer-management/monitor.ts
Bump subgraph query page size to 1000 as per #1058 
Also fixes subgraph pagination that sometimes results in duplicates in this test:
https://github.com/graphprotocol/indexer/blob/main/packages/indexer-common/src/indexer-management/__tests__/helpers.test.ts#L355
Which is leading to this failure in tests sometimes:
https://github.com/graphprotocol/indexer/actions/runs/12281805281/job/34271522211?pr=1055
```
@graphprotocol/indexer-common:   ● Monitor: CI › Fetch subgraphs
@graphprotocol/indexer-common:     expect(received).toEqual(expected) // deep equality
@graphprotocol/indexer-common:     Expected: 106
@graphprotocol/indexer-common:     Received: 107
@graphprotocol/indexer-common: 
@graphprotocol/indexer-common:       461 |       'HGZgSEpRbwY3H54vyrUfqn8RXqDA23qT9yLqyxZXZTNW', …
```
> common: fix subgraph pagination

- packages/indexer-common/src/indexer-management/monitor.ts
I was running the Indexer Agent and after a few days I realized the amount of queries it sent to the network subgraphs was out of proportion and quickly draining my api key.
The Indexer Agent performs a number of “housekeeping” queries at regular periods of time to sync with the latest network status.
One of those queries gets the entire set of subgraphs on the network but it does so paginating by 10 items batches. With the current number of subgraphs over 10,000, it takes more than 1,000 queries to get them all.
The eventual runs every 120 seconds, that means it's sending about 720,000 queries a day.
Set the `first` parameter to `1000` for the query within `subgraphDeployments` function of the `NetworkMonitor.`
> fix: optimize the round trips when reconciling the subgraph deployments 

- packages/indexer-common/src/allocations/__tests__/tap.test.ts
- packages/indexer-common/src/allocations/tap-collector.ts
Signed-off-by: Gustavo Inacio <gustavo@semiotic.ai>
> common: fix errors when there're a lot of ravs pending

- packages/indexer-agent/src/agent.ts
- packages/indexer-common/src/allocations/tap-collector.ts
- packages/indexer-common/src/graph-node.ts
- packages/indexer-common/src/indexer-management/actions.ts
- packages/indexer-common/src/indexer-management/allocations.ts
- packages/indexer-common/src/indexer-management/monitor.ts
- packages/indexer-common/src/indexer-management/resolvers/allocations.ts
- packages/indexer-common/src/network.ts
- packages/indexer-common/src/sequential-timer.ts
This PR is an optimization for where the graph-node has thousands of active deployments, and calling the `indexerStatus` endpoint is taking a long time for the upgrade indexer.
> issue: action-batch

- packages/indexer-common/src/indexer-management/actions.ts
This PR marks actions as PENDING while they are being executed. Out of this we can remove the dependency on a long-lived database transaction that can time out and fail while execution may have succeeded.
This attempts to address a couple of issues that have shown up lately:
1. Contract execution fails sometimes, maybe due to estimateGas failing or if an allocation is already present for an action being executed (stale network state)
2. A long-live database transaction has timed out, leading to issue 1. after the next execution of a batch.
The behavior I've opted for here is: success and failures during execution result in the same behavior as before, however if there is an _exception_ during execution, (such as from interacting with graph-node or from the contracts), then the Action is …
> mark actions as PENDING while executing

- packages/indexer-common/src/indexer-management/types.ts
This supports shorter network aliases stripped of their -mainnet suffix, if it's present.
> common: also add chain aliases stripped of their -mainnet suffix

- docs/action-queue.md
- docs/networks/arbitrum-sepolia.md
- packages/indexer-agent/src/__tests__/indexer.ts
- packages/indexer-agent/src/commands/common-options.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-agent/src/db/migrations/18-actions-expand-action-status-add-deploying.ts
- packages/indexer-cli/src/__tests__/indexer/cost.test.ts
- packages/indexer-cli/src/__tests__/util.ts
- packages/indexer-cli/src/commands/indexer/actions/delete.ts
- packages/indexer-cli/src/commands/indexer/actions/get.ts
- packages/indexer-cli/src/commands/indexer/actions/update.ts
- packages/indexer-common/src/__tests__/ipfs.test.ts
- packages/indexer-common/src/actions.ts
- packages/indexer-common/src/allocations/__tests__/tap.test.ts
- packages/indexer-common/src/allocations/__tests__/validate-queries.test.ts
- packages/indexer-common/src/graph-node.ts
- packages/indexer-common/src/indexer-management/__tests__/allocations.test.ts
- packages/indexer-common/src/indexer-management/__tests__/helpers.test.ts
- packages/indexer-common/src/indexer-management/__tests__/util.ts
- packages/indexer-common/src/indexer-management/actions.ts
- packages/indexer-common/src/indexer-management/allocations.ts
- packages/indexer-common/src/indexer-management/client.ts
- packages/indexer-common/src/indexer-management/models/action.ts
- packages/indexer-common/src/indexer-management/resolvers/indexer-status.ts
- packages/indexer-common/src/subgraph-client.ts
closes #439 
Adds behavior: when an ipfs endpoint is specified, we can crawl subgraph manifests and deploy the dependencies needed to make the graft successful.
This PR adds a new migration and ActionStatus enum variant "deploying" in order to more carefully implement re-entrance for the action execution flow.
> agent,cli,common: feature - auto graft sync

- .gitignore
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-common/src/network-specification.ts
- packages/indexer-common/src/network.ts
Signed-off-by: Tomás Migone <tomas@edgeandnode.com>
> feat: support split address books

- .gitignore
- packages/indexer-agent/src/agent.ts
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-common/package.json
- packages/indexer-common/src/__tests__/network-specification-files/invalid-payments-destination.yml
- packages/indexer-common/src/__tests__/network-specification-files/invalid-provision-size.yml
- packages/indexer-common/src/__tests__/network-specification-files/valid.yml
- packages/indexer-common/src/__tests__/network-specification.test.ts
- packages/indexer-common/src/network-specification.ts
- packages/indexer-common/src/network.ts
- yarn.lock
Signed-off-by: Tomás Migone <tomas@edgeandnode.com>
> feat: update registration to support horizon flow, add provisioning flow at startup

- README.md
- packages/indexer-agent/src/commands/start.ts
- packages/indexer-common/package.json
- packages/indexer-common/src/indexer-management/models/cost-model.ts
- packages/indexer-common/src/indexer-management/models/indexing-rule.ts
- packages/indexer-common/src/indexer-management/models/poi-dispute.ts
- packages/indexer-common/src/network-specification.ts
- packages/indexer-common/src/network.ts
- packages/indexer-common/src/transactions.ts
- yarn.lock
Signed-off-by: Tomás Migone <tomas@edgeandnode.com>
> Horizon fixes

- packages/indexer-common/src/indexer-management/models/cost-model.ts
- packages/indexer-common/src/indexer-management/models/indexing-rule.ts
- packages/indexer-common/src/indexer-management/models/poi-dispute.ts
This fixes an issue where model public fields shadow sequelize setters/getters making models's actual data undefined.
```
indexer-agent  | (sequelize) Warning: Model "IndexingRule" is declaring public class fields for attribute(s): "id", "identifier", "identifierType", "allocationAmount", "allocationLifetime", "autoRenewal", "parallelAllocations", "maxAllocationPercentage", "minSignal", "minStake", "maxSignal", "minAverageQueryFees", "custom", "decisionBasis", "requireSupported", "safety", "protocolNetwork", "createdAt", "updatedAt".
indexer-agent  | These class fields are shadowing Sequelize's attribute getters & setters.
indexer-agent  | See https://sequelize.org/main/manual/model-basics.html#caveat-with-public-class-fields
```
For details see …
> fix: sequelize field shadowing in models

- docs/feature-support-matrix.md
With the release of `graph-node 0.39.0`, arweave support was deprecated, so we add a new `Deprecated` column for tracking purposes.
Additionally, a typo was fixed (`artbitrum -> arbitrum`)
> Bump graph-node in feature support matrix
